%------------------
% CONNECTIONS
%------------------


% parameters:
%	User 1
%	User 2
%	Connection strengh
%		- 1: Colleagues
%		- 2: Friends
%		- 3: Family
%	Connection Tag


%--------------------------------


:-dynamic ligacao/4.

%ligacao('Sarah Silva', 'Pedro Mourao',2,31).
%ligacao('Pedro Mourao', 'Sarah Silva',3,11).

ligacao('Sarah Silva', 'Rafael Soares', 3, -43).
ligacao('Sarah Silva', 'Dario Ornelas', 3, 4).
ligacao('Sarah Silva', 'Yuri Serralheiro', 3, 25).
ligacao('Sarah Silva', 'Francisco Vilar', 3, 11).
ligacao('Sarah Silva', 'Nancy Sodre', 3, 14).
ligacao('Sarah Silva', 'David Correia', 1, 24).
ligacao('Sarah Silva', 'Flora Quental', 3, 22).
ligacao('Pedro Mourao', 'Maria Francisca', 3, 46).
ligacao('Pedro Mourao', 'Rui Duraes', 3, 7).
ligacao('Pedro Mourao', 'Rui Pedro', 2, 16).
ligacao('Pedro Mourao', 'Alice Monforte', 2, 14).
ligacao('Pedro Mourao', 'Antero Ouro', 2, 11).
ligacao('Pedro Mourao', 'Rafaela Uria', 2, 17).
ligacao('Pedro Mourao', 'Liliana Infante', 1, 45).
ligacao('Rafael Soares', 'Sarah Silva', 1, 7).
ligacao('Rafael Soares', 'Fabio Silva', 2, 23).
ligacao('Rafael Soares', 'Jonatas Granjeiro', 2, 10).
ligacao('Rafael Soares', 'Marco Gravato', 1, 19).
ligacao('Rafael Soares', 'Denzel Rufino', 2, 8).
ligacao('Rafael Soares', 'Joao Bulhosa', 2, -6).
ligacao('Rafael Soares', 'Ana Camarinho', 1, 48).
ligacao('Rafael Soares', 'Mia Carvalho', 1, 24).
ligacao('Dario Ornelas', 'Sarah Silva', 3, -8).
ligacao('Dario Ornelas', 'Fabio Silva', 2, 47).
ligacao('Dario Ornelas', 'Jonatas Granjeiro', 1, 28).
ligacao('Dario Ornelas', 'Marco Gravato', 2, 46).
ligacao('Dario Ornelas', 'Denzel Rufino', 3, 17).
ligacao('Dario Ornelas', 'Joao Bulhosa', 1, -10).
ligacao('Dario Ornelas', 'Ana Camarinho', 1, 19).
ligacao('Dario Ornelas', 'Mia Carvalho', 2, 49).
ligacao('Yuri Serralheiro', 'Sarah Silva', 2, -10).
ligacao('Yuri Serralheiro', 'Fabio Silva', 2, 27).
ligacao('Yuri Serralheiro', 'Jonatas Granjeiro', 1, -7).
ligacao('Yuri Serralheiro', 'Marco Gravato', 3, 0).
ligacao('Yuri Serralheiro', 'Denzel Rufino', 1, 38).
ligacao('Yuri Serralheiro', 'Joao Bulhosa', 2, 0).
ligacao('Yuri Serralheiro', 'Ana Camarinho', 1, 32).
ligacao('Yuri Serralheiro', 'Mia Carvalho', 3, 19).
ligacao('Francisco Vilar', 'Sarah Silva', 3, 16).
ligacao('Francisco Vilar', 'Fabio Silva', 2, -4).
ligacao('Francisco Vilar', 'Jonatas Granjeiro', 3, 9).
ligacao('Francisco Vilar', 'Marco Gravato', 3, -1).
ligacao('Francisco Vilar', 'Denzel Rufino', 1, 7).
ligacao('Francisco Vilar', 'Joao Bulhosa', 3, -9).
ligacao('Francisco Vilar', 'Ana Camarinho', 3, 31).
ligacao('Francisco Vilar', 'Mia Carvalho', 1, 21).
ligacao('Nancy Sodre', 'Sarah Silva', 2, 10).
ligacao('Nancy Sodre', 'Fabio Silva', 1, 41).
ligacao('Nancy Sodre', 'Jonatas Granjeiro', 3, 31).
ligacao('Nancy Sodre', 'Marco Gravato', 1, 44).
ligacao('Nancy Sodre', 'Denzel Rufino', 2, 1).
ligacao('Nancy Sodre', 'Joao Bulhosa', 1, 34).
ligacao('Nancy Sodre', 'Ana Camarinho', 3, 25).
ligacao('Nancy Sodre', 'Mia Carvalho', 1, 21).
ligacao('David Correia', 'Sarah Silva', 1, 28).
ligacao('David Correia', 'Fabio Silva', 1, 22).
ligacao('David Correia', 'Jonatas Granjeiro', 3, -6).
ligacao('David Correia', 'Marco Gravato', 2, 12).
ligacao('David Correia', 'Denzel Rufino', 3, 46).
ligacao('David Correia', 'Joao Bulhosa', 2, -8).
ligacao('David Correia', 'Ana Camarinho', 1, 32).
ligacao('David Correia', 'Mia Carvalho', 3, 49).
ligacao('Flora Quental', 'Sarah Silva', 3, 3).
ligacao('Flora Quental', 'Fabio Silva', 3, -8).
ligacao('Flora Quental', 'Jonatas Granjeiro', 1, 38).
ligacao('Flora Quental', 'Marco Gravato', 2, -4).
ligacao('Flora Quental', 'Denzel Rufino', 1, 15).
ligacao('Flora Quental', 'Joao Bulhosa', 2, 41).
ligacao('Flora Quental', 'Ana Camarinho', 2, 39).
ligacao('Flora Quental', 'Mia Carvalho', 1, 14).
ligacao('Fabio Silva', 'Rafael Soares', 1, 5).
ligacao('Fabio Silva', 'Dario Ornelas', 2, 23).
ligacao('Fabio Silva', 'Yuri Serralheiro', 1, 24).
ligacao('Fabio Silva', 'Francisco Vilar', 1, 45).
ligacao('Fabio Silva', 'Nancy Sodre', 2, 10).
ligacao('Fabio Silva', 'David Correia', 3, 34).
ligacao('Fabio Silva', 'Flora Quental', 3, 18).
ligacao('Fabio Silva', 'Carlos Moutinho', 1, 31).
ligacao('Fabio Silva', 'Breno Granja', 3, 13).
ligacao('Fabio Silva', 'Rodrigo Sousa', 3, 47).
ligacao('Fabio Silva', 'Andreia Sousa', 3, 35).
ligacao('Fabio Silva', 'Deolinda Varzeas', 3, 40).
ligacao('Fabio Silva', 'Beatriz Varzeas', 1, 20).
ligacao('Fabio Silva', 'Antonio Morais', 3, 6).
ligacao('Jonatas Granjeiro', 'Rafael Soares', 2, 41).
ligacao('Jonatas Granjeiro', 'Dario Ornelas', 1, 8).
ligacao('Jonatas Granjeiro', 'Yuri Serralheiro', 3, -3).
ligacao('Jonatas Granjeiro', 'Francisco Vilar', 1, 50).
ligacao('Jonatas Granjeiro', 'Nancy Sodre', 2, 38).
ligacao('Jonatas Granjeiro', 'David Correia', 2, 0).
ligacao('Jonatas Granjeiro', 'Flora Quental', 2, 18).
ligacao('Jonatas Granjeiro', 'Carlos Moutinho', 1, 11).
ligacao('Jonatas Granjeiro', 'Breno Granja', 3, 46).
ligacao('Jonatas Granjeiro', 'Rodrigo Sousa', 1, 45).
ligacao('Jonatas Granjeiro', 'Andreia Sousa', 2, 30).
ligacao('Jonatas Granjeiro', 'Deolinda Varzeas', 2, 30).
ligacao('Jonatas Granjeiro', 'Beatriz Varzeas', 2, 15).
ligacao('Jonatas Granjeiro', 'Antonio Morais', 1, -4).
ligacao('Marco Gravato', 'Rafael Soares', 3, 23).
ligacao('Marco Gravato', 'Dario Ornelas', 3, 12).
ligacao('Marco Gravato', 'Yuri Serralheiro', 1, 14).
ligacao('Marco Gravato', 'Francisco Vilar', 2, -3).
ligacao('Marco Gravato', 'Nancy Sodre', 2, 22).
ligacao('Marco Gravato', 'David Correia', 2, 1).
ligacao('Marco Gravato', 'Flora Quental', 3, 29).
ligacao('Marco Gravato', 'Carlos Moutinho', 3, 0).
ligacao('Marco Gravato', 'Breno Granja', 3, 13).
ligacao('Marco Gravato', 'Rodrigo Sousa', 1, 26).
ligacao('Marco Gravato', 'Andreia Sousa', 2, 33).
ligacao('Marco Gravato', 'Deolinda Varzeas', 1, 44).
ligacao('Marco Gravato', 'Beatriz Varzeas', 2, 24).
ligacao('Marco Gravato', 'Antonio Morais', 3, 23).
ligacao('Denzel Rufino', 'Rafael Soares', 2, 13).
ligacao('Denzel Rufino', 'Dario Ornelas', 2, -8).
ligacao('Denzel Rufino', 'Yuri Serralheiro', 3, 25).
ligacao('Denzel Rufino', 'Francisco Vilar', 1, 25).
ligacao('Denzel Rufino', 'Nancy Sodre', 2, 4).
ligacao('Denzel Rufino', 'David Correia', 3, 42).
ligacao('Denzel Rufino', 'Flora Quental', 3, 4).
ligacao('Denzel Rufino', 'Carlos Moutinho', 2, 29).
ligacao('Denzel Rufino', 'Breno Granja', 3, 15).
ligacao('Denzel Rufino', 'Rodrigo Sousa', 3, 45).
ligacao('Denzel Rufino', 'Andreia Sousa', 1, 30).
ligacao('Denzel Rufino', 'Deolinda Varzeas', 1, 27).
ligacao('Denzel Rufino', 'Beatriz Varzeas', 3, 11).
ligacao('Denzel Rufino', 'Antonio Morais', 2, 42).
ligacao('Joao Bulhosa', 'Rafael Soares', 2, -1).
ligacao('Joao Bulhosa', 'Dario Ornelas', 1, 31).
ligacao('Joao Bulhosa', 'Yuri Serralheiro', 2, 3).
ligacao('Joao Bulhosa', 'Francisco Vilar', 1, 30).
ligacao('Joao Bulhosa', 'Nancy Sodre', 1, 17).
ligacao('Joao Bulhosa', 'David Correia', 2, 21).
ligacao('Joao Bulhosa', 'Flora Quental', 3, -10).
ligacao('Joao Bulhosa', 'Carlos Moutinho', 3, 38).
ligacao('Joao Bulhosa', 'Breno Granja', 1, -4).
ligacao('Joao Bulhosa', 'Rodrigo Sousa', 3, 45).
ligacao('Joao Bulhosa', 'Andreia Sousa', 3, 14).
ligacao('Joao Bulhosa', 'Deolinda Varzeas', 1, -1).
ligacao('Joao Bulhosa', 'Beatriz Varzeas', 3, 18).
ligacao('Joao Bulhosa', 'Antonio Morais', 2, 1).
ligacao('Ana Camarinho', 'Rafael Soares', 1, 45).
ligacao('Ana Camarinho', 'Dario Ornelas', 1, -10).
ligacao('Ana Camarinho', 'Yuri Serralheiro', 2, 48).
ligacao('Ana Camarinho', 'Francisco Vilar', 3, 27).
ligacao('Ana Camarinho', 'Nancy Sodre', 1, 12).
ligacao('Ana Camarinho', 'David Correia', 1, 23).
ligacao('Ana Camarinho', 'Flora Quental', 1, 24).
ligacao('Ana Camarinho', 'Carlos Moutinho', 2, 5).
ligacao('Ana Camarinho', 'Breno Granja', 2, -3).
ligacao('Ana Camarinho', 'Rodrigo Sousa', 3, 28).
ligacao('Ana Camarinho', 'Andreia Sousa', 2, 9).
ligacao('Ana Camarinho', 'Deolinda Varzeas', 1, -10).
ligacao('Ana Camarinho', 'Beatriz Varzeas', 3, 5).
ligacao('Ana Camarinho', 'Antonio Morais', 3, 1).
ligacao('Mia Carvalho', 'Rafael Soares', 2, 45).
ligacao('Mia Carvalho', 'Dario Ornelas', 1, 32).
ligacao('Mia Carvalho', 'Yuri Serralheiro', 2, 12).
ligacao('Mia Carvalho', 'Francisco Vilar', 1, 45).
ligacao('Mia Carvalho', 'Nancy Sodre', 1, 13).
ligacao('Mia Carvalho', 'David Correia', 1, 30).
ligacao('Mia Carvalho', 'Flora Quental', 1, -6).
ligacao('Mia Carvalho', 'Carlos Moutinho', 3, 40).
ligacao('Mia Carvalho', 'Breno Granja', 3, -9).
ligacao('Mia Carvalho', 'Rodrigo Sousa', 3, 4).
ligacao('Mia Carvalho', 'Andreia Sousa', 1, 32).
ligacao('Mia Carvalho', 'Deolinda Varzeas', 1, -3).
ligacao('Mia Carvalho', 'Beatriz Varzeas', 1, 43).
ligacao('Mia Carvalho', 'Antonio Morais', 3, 24).
ligacao('Carlos Moutinho', 'Fabio Silva', 2, 27).
ligacao('Carlos Moutinho', 'Jonatas Granjeiro', 2, 32).
ligacao('Carlos Moutinho', 'Marco Gravato', 3, 16).
ligacao('Carlos Moutinho', 'Denzel Rufino', 3, 35).
ligacao('Carlos Moutinho', 'Joao Bulhosa', 3, 13).
ligacao('Carlos Moutinho', 'Ana Camarinho', 1, 44).
ligacao('Carlos Moutinho', 'Mia Carvalho', 3, 25).
ligacao('Carlos Moutinho', 'Rui Mariske', 3, 48).
ligacao('Carlos Moutinho', 'Lisandra Batata', 1, 6).
ligacao('Carlos Moutinho', 'Alma Velasco', 3, 47).
ligacao('Carlos Moutinho', 'Zavier Salomao', 3, 16).
ligacao('Carlos Moutinho', 'Xavier Alcaide', 3, 41).
ligacao('Carlos Moutinho', 'Teresa Barbosa', 2, 43).
ligacao('Carlos Moutinho', 'Helena Peixoto', 1, 42).
ligacao('Breno Granja', 'Fabio Silva', 3, -6).
ligacao('Breno Granja', 'Jonatas Granjeiro', 1, -9).
ligacao('Breno Granja', 'Marco Gravato', 2, 46).
ligacao('Breno Granja', 'Denzel Rufino', 1, 46).
ligacao('Breno Granja', 'Joao Bulhosa', 2, 13).
ligacao('Breno Granja', 'Ana Camarinho', 1, 31).
ligacao('Breno Granja', 'Mia Carvalho', 2, 8).
ligacao('Breno Granja', 'Rui Mariske', 3, 20).
ligacao('Breno Granja', 'Lisandra Batata', 3, -1).
ligacao('Breno Granja', 'Alma Velasco', 1, 3).
ligacao('Breno Granja', 'Zavier Salomao', 3, 1).
ligacao('Breno Granja', 'Xavier Alcaide', 1, 23).
ligacao('Breno Granja', 'Teresa Barbosa', 2, -8).
ligacao('Breno Granja', 'Helena Peixoto', 2, 5).
ligacao('Rodrigo Sousa', 'Fabio Silva', 3, 22).
ligacao('Rodrigo Sousa', 'Jonatas Granjeiro', 3, 11).
ligacao('Rodrigo Sousa', 'Marco Gravato', 1, 44).
ligacao('Rodrigo Sousa', 'Denzel Rufino', 2, 15).
ligacao('Rodrigo Sousa', 'Joao Bulhosa', 2, 38).
ligacao('Rodrigo Sousa', 'Ana Camarinho', 2, 14).
ligacao('Rodrigo Sousa', 'Mia Carvalho', 3, -3).
ligacao('Rodrigo Sousa', 'Rui Mariske', 3, -4).
ligacao('Rodrigo Sousa', 'Lisandra Batata', 2, 23).
ligacao('Rodrigo Sousa', 'Alma Velasco', 1, -3).
ligacao('Rodrigo Sousa', 'Zavier Salomao', 2, 1).
ligacao('Rodrigo Sousa', 'Xavier Alcaide', 1, -3).
ligacao('Rodrigo Sousa', 'Teresa Barbosa', 2, 47).
ligacao('Rodrigo Sousa', 'Helena Peixoto', 2, 12).
ligacao('Andreia Sousa', 'Fabio Silva', 2, 22).
ligacao('Andreia Sousa', 'Jonatas Granjeiro', 3, 0).
ligacao('Andreia Sousa', 'Marco Gravato', 3, 35).
ligacao('Andreia Sousa', 'Denzel Rufino', 3, 8).
ligacao('Andreia Sousa', 'Joao Bulhosa', 1, 28).
ligacao('Andreia Sousa', 'Ana Camarinho', 1, 4).
ligacao('Andreia Sousa', 'Mia Carvalho', 2, 3).
ligacao('Andreia Sousa', 'Rui Mariske', 2, 20).
ligacao('Andreia Sousa', 'Lisandra Batata', 2, -6).
ligacao('Andreia Sousa', 'Alma Velasco', 1, -10).
ligacao('Andreia Sousa', 'Zavier Salomao', 1, 3).
ligacao('Andreia Sousa', 'Xavier Alcaide', 1, 46).
ligacao('Andreia Sousa', 'Teresa Barbosa', 2, 5).
ligacao('Andreia Sousa', 'Helena Peixoto', 1, 4).
ligacao('Deolinda Varzeas', 'Fabio Silva', 2, 21).
ligacao('Deolinda Varzeas', 'Jonatas Granjeiro', 1, 18).
ligacao('Deolinda Varzeas', 'Marco Gravato', 1, -6).
ligacao('Deolinda Varzeas', 'Denzel Rufino', 2, 48).
ligacao('Deolinda Varzeas', 'Joao Bulhosa', 3, 27).
ligacao('Deolinda Varzeas', 'Ana Camarinho', 2, -8).
ligacao('Deolinda Varzeas', 'Mia Carvalho', 2, 23).
ligacao('Deolinda Varzeas', 'Rui Mariske', 3, 36).
ligacao('Deolinda Varzeas', 'Lisandra Batata', 3, 0).
ligacao('Deolinda Varzeas', 'Alma Velasco', 1, 18).
ligacao('Deolinda Varzeas', 'Zavier Salomao', 1, 45).
ligacao('Deolinda Varzeas', 'Xavier Alcaide', 1, 47).
ligacao('Deolinda Varzeas', 'Teresa Barbosa', 1, -10).
ligacao('Deolinda Varzeas', 'Helena Peixoto', 2, 40).
ligacao('Beatriz Varzeas', 'Fabio Silva', 3, 9).
ligacao('Beatriz Varzeas', 'Jonatas Granjeiro', 3, 19).
ligacao('Beatriz Varzeas', 'Marco Gravato', 2, 5).
ligacao('Beatriz Varzeas', 'Denzel Rufino', 2, 19).
ligacao('Beatriz Varzeas', 'Joao Bulhosa', 2, -4).
ligacao('Beatriz Varzeas', 'Ana Camarinho', 3, 38).
ligacao('Beatriz Varzeas', 'Mia Carvalho', 1, 35).
ligacao('Beatriz Varzeas', 'Rui Mariske', 3, 17).
ligacao('Beatriz Varzeas', 'Lisandra Batata', 1, 49).
ligacao('Beatriz Varzeas', 'Alma Velasco', 2, 12).
ligacao('Beatriz Varzeas', 'Zavier Salomao', 3, 17).
ligacao('Beatriz Varzeas', 'Xavier Alcaide', 2, 47).
ligacao('Beatriz Varzeas', 'Teresa Barbosa', 3, 50).
ligacao('Beatriz Varzeas', 'Helena Peixoto', 2, 37).
ligacao('Antonio Morais', 'Fabio Silva', 1, 5).
ligacao('Antonio Morais', 'Jonatas Granjeiro', 2, 38).
ligacao('Antonio Morais', 'Marco Gravato', 2, 18).
ligacao('Antonio Morais', 'Denzel Rufino', 1, -7).
ligacao('Antonio Morais', 'Joao Bulhosa', 1, -9).
ligacao('Antonio Morais', 'Ana Camarinho', 2, 36).
ligacao('Antonio Morais', 'Mia Carvalho', 3, 0).
ligacao('Antonio Morais', 'Rui Mariske', 3, -5).
ligacao('Antonio Morais', 'Lisandra Batata', 2, 25).
ligacao('Antonio Morais', 'Alma Velasco', 3, 42).
ligacao('Antonio Morais', 'Zavier Salomao', 2, 22).
ligacao('Antonio Morais', 'Xavier Alcaide', 3, 45).
ligacao('Antonio Morais', 'Teresa Barbosa', 3, 49).
ligacao('Antonio Morais', 'Helena Peixoto', 2, 38).
ligacao('Rui Mariske', 'Carlos Moutinho', 1, -10).
ligacao('Rui Mariske', 'Breno Granja', 1, -7).
ligacao('Rui Mariske', 'Rodrigo Sousa', 3, 43).
ligacao('Rui Mariske', 'Andreia Sousa', 1, 7).
ligacao('Rui Mariske', 'Deolinda Varzeas', 2, 39).
ligacao('Rui Mariske', 'Beatriz Varzeas', 3, 15).
ligacao('Rui Mariske', 'Antonio Morais', 1, 21).
ligacao('Rui Mariske', 'Rosa Machado', 1, 29).
ligacao('Rui Mariske', 'Guilherme Araujo', 3, 18).
ligacao('Rui Mariske', 'Joana Araujo', 1, 41).
ligacao('Rui Mariske', 'Alberto Estrela', 1, 47).
ligacao('Rui Mariske', 'Alberto Camara', 1, -7).
ligacao('Rui Mariske', 'Diana Chaves', 3, 9).
ligacao('Rui Mariske', 'Joao Prada', 2, 3).
ligacao('Lisandra Batata', 'Carlos Moutinho', 3, 10).
ligacao('Lisandra Batata', 'Breno Granja', 2, 6).
ligacao('Lisandra Batata', 'Rodrigo Sousa', 3, 4).
ligacao('Lisandra Batata', 'Andreia Sousa', 2, 1).
ligacao('Lisandra Batata', 'Deolinda Varzeas', 2, 40).
ligacao('Lisandra Batata', 'Beatriz Varzeas', 1, 47).
ligacao('Lisandra Batata', 'Antonio Morais', 3, 31).
ligacao('Lisandra Batata', 'Rosa Machado', 1, 27).
ligacao('Lisandra Batata', 'Guilherme Araujo', 2, 35).
ligacao('Lisandra Batata', 'Joana Araujo', 3, 32).
ligacao('Lisandra Batata', 'Alberto Estrela', 1, 26).
ligacao('Lisandra Batata', 'Alberto Camara', 1, 16).
ligacao('Lisandra Batata', 'Diana Chaves', 3, 7).
ligacao('Lisandra Batata', 'Joao Prada', 2, 4).
ligacao('Alma Velasco', 'Carlos Moutinho', 1, 28).
ligacao('Alma Velasco', 'Breno Granja', 2, 34).
ligacao('Alma Velasco', 'Rodrigo Sousa', 3, 41).
ligacao('Alma Velasco', 'Andreia Sousa', 2, 46).
ligacao('Alma Velasco', 'Deolinda Varzeas', 2, 39).
ligacao('Alma Velasco', 'Beatriz Varzeas', 3, -7).
ligacao('Alma Velasco', 'Antonio Morais', 3, 30).
ligacao('Alma Velasco', 'Rosa Machado', 3, 47).
ligacao('Alma Velasco', 'Guilherme Araujo', 2, 8).
ligacao('Alma Velasco', 'Joana Araujo', 2, 32).
ligacao('Alma Velasco', 'Alberto Estrela', 1, 3).
ligacao('Alma Velasco', 'Alberto Camara', 2, 11).
ligacao('Alma Velasco', 'Diana Chaves', 3, 12).
ligacao('Alma Velasco', 'Joao Prada', 1, 21).
ligacao('Zavier Salomao', 'Carlos Moutinho', 1, 50).
ligacao('Zavier Salomao', 'Breno Granja', 3, 12).
ligacao('Zavier Salomao', 'Rodrigo Sousa', 1, 14).
ligacao('Zavier Salomao', 'Andreia Sousa', 3, -10).
ligacao('Zavier Salomao', 'Deolinda Varzeas', 3, 19).
ligacao('Zavier Salomao', 'Beatriz Varzeas', 3, 25).
ligacao('Zavier Salomao', 'Antonio Morais', 1, 14).
ligacao('Zavier Salomao', 'Rosa Machado', 2, -4).
ligacao('Zavier Salomao', 'Guilherme Araujo', 3, 28).
ligacao('Zavier Salomao', 'Joana Araujo', 2, 31).
ligacao('Zavier Salomao', 'Alberto Estrela', 1, 30).
ligacao('Zavier Salomao', 'Alberto Camara', 1, 47).
ligacao('Zavier Salomao', 'Diana Chaves', 2, 30).
ligacao('Zavier Salomao', 'Joao Prada', 1, 40).
ligacao('Xavier Alcaide', 'Carlos Moutinho', 3, 3).
ligacao('Xavier Alcaide', 'Breno Granja', 2, 33).
ligacao('Xavier Alcaide', 'Rodrigo Sousa', 3, 49).
ligacao('Xavier Alcaide', 'Andreia Sousa', 3, 32).
ligacao('Xavier Alcaide', 'Deolinda Varzeas', 1, -1).
ligacao('Xavier Alcaide', 'Beatriz Varzeas', 3, -3).
ligacao('Xavier Alcaide', 'Antonio Morais', 1, 37).
ligacao('Xavier Alcaide', 'Rosa Machado', 1, 37).
ligacao('Xavier Alcaide', 'Guilherme Araujo', 3, 50).
ligacao('Xavier Alcaide', 'Joana Araujo', 2, 4).
ligacao('Xavier Alcaide', 'Alberto Estrela', 3, 40).
ligacao('Xavier Alcaide', 'Alberto Camara', 2, 42).
ligacao('Xavier Alcaide', 'Diana Chaves', 3, 3).
ligacao('Xavier Alcaide', 'Joao Prada', 2, 25).
ligacao('Teresa Barbosa', 'Carlos Moutinho', 3, 9).
ligacao('Teresa Barbosa', 'Breno Granja', 2, 39).
ligacao('Teresa Barbosa', 'Rodrigo Sousa', 1, -4).
ligacao('Teresa Barbosa', 'Andreia Sousa', 1, 33).
ligacao('Teresa Barbosa', 'Deolinda Varzeas', 3, 1).
ligacao('Teresa Barbosa', 'Beatriz Varzeas', 1, 12).
ligacao('Teresa Barbosa', 'Antonio Morais', 3, 38).
ligacao('Teresa Barbosa', 'Rosa Machado', 1, 33).
ligacao('Teresa Barbosa', 'Guilherme Araujo', 3, 5).
ligacao('Teresa Barbosa', 'Joana Araujo', 2, 42).
ligacao('Teresa Barbosa', 'Alberto Estrela', 3, 48).
ligacao('Teresa Barbosa', 'Alberto Camara', 2, 34).
ligacao('Teresa Barbosa', 'Diana Chaves', 1, 33).
ligacao('Teresa Barbosa', 'Joao Prada', 2, 47).
ligacao('Helena Peixoto', 'Carlos Moutinho', 2, 16).
ligacao('Helena Peixoto', 'Breno Granja', 2, 48).
ligacao('Helena Peixoto', 'Rodrigo Sousa', 3, -3).
ligacao('Helena Peixoto', 'Andreia Sousa', 1, 18).
ligacao('Helena Peixoto', 'Deolinda Varzeas', 2, 29).
ligacao('Helena Peixoto', 'Beatriz Varzeas', 3, 26).
ligacao('Helena Peixoto', 'Antonio Morais', 2, 34).
ligacao('Helena Peixoto', 'Rosa Machado', 2, 10).
ligacao('Helena Peixoto', 'Guilherme Araujo', 1, 30).
ligacao('Helena Peixoto', 'Joana Araujo', 2, 9).
ligacao('Helena Peixoto', 'Alberto Estrela', 3, -6).
ligacao('Helena Peixoto', 'Alberto Camara', 1, 21).
ligacao('Helena Peixoto', 'Diana Chaves', 1, 12).
ligacao('Helena Peixoto', 'Joao Prada', 1, -8).
ligacao('Rosa Machado', 'Rui Mariske', 3, 17).
ligacao('Rosa Machado', 'Lisandra Batata', 1, 27).
ligacao('Rosa Machado', 'Alma Velasco', 3, -6).
ligacao('Rosa Machado', 'Zavier Salomao', 1, 26).
ligacao('Rosa Machado', 'Xavier Alcaide', 2, 5).
ligacao('Rosa Machado', 'Teresa Barbosa', 2, 9).
ligacao('Rosa Machado', 'Helena Peixoto', 3, 35).
ligacao('Rosa Machado', 'Telmo Catarino', 2, 14).
ligacao('Rosa Machado', 'Guilherme Vital', 1, 14).
ligacao('Rosa Machado', 'Rita Brandao', 2, 12).
ligacao('Rosa Machado', 'Sara Homem', 1, 0).
ligacao('Rosa Machado', 'Veronica Colaca', 1, 45).
ligacao('Rosa Machado', 'Emilia Monforte', 1, 10).
ligacao('Rosa Machado', 'Olivia Vidal', 3, 28).
ligacao('Guilherme Araujo', 'Rui Mariske', 1, 24).
ligacao('Guilherme Araujo', 'Lisandra Batata', 2, 11).
ligacao('Guilherme Araujo', 'Alma Velasco', 1, -10).
ligacao('Guilherme Araujo', 'Zavier Salomao', 3, 5).
ligacao('Guilherme Araujo', 'Xavier Alcaide', 2, 30).
ligacao('Guilherme Araujo', 'Teresa Barbosa', 1, 40).
ligacao('Guilherme Araujo', 'Helena Peixoto', 3, 25).
ligacao('Guilherme Araujo', 'Telmo Catarino', 3, 8).
ligacao('Guilherme Araujo', 'Guilherme Vital', 3, 45).
ligacao('Guilherme Araujo', 'Rita Brandao', 2, 12).
ligacao('Guilherme Araujo', 'Sara Homem', 3, 48).
ligacao('Guilherme Araujo', 'Veronica Colaca', 2, 28).
ligacao('Guilherme Araujo', 'Emilia Monforte', 1, 12).
ligacao('Guilherme Araujo', 'Olivia Vidal', 3, 14).
ligacao('Joana Araujo', 'Rui Mariske', 2, 45).
ligacao('Joana Araujo', 'Lisandra Batata', 3, 7).
ligacao('Joana Araujo', 'Alma Velasco', 3, 35).
ligacao('Joana Araujo', 'Zavier Salomao', 1, 7).
ligacao('Joana Araujo', 'Xavier Alcaide', 1, 49).
ligacao('Joana Araujo', 'Teresa Barbosa', 2, 0).
ligacao('Joana Araujo', 'Helena Peixoto', 1, -6).
ligacao('Joana Araujo', 'Telmo Catarino', 1, 21).
ligacao('Joana Araujo', 'Guilherme Vital', 3, 11).
ligacao('Joana Araujo', 'Rita Brandao', 2, 27).
ligacao('Joana Araujo', 'Sara Homem', 3, -5).
ligacao('Joana Araujo', 'Veronica Colaca', 3, -10).
ligacao('Joana Araujo', 'Emilia Monforte', 3, -9).
ligacao('Joana Araujo', 'Olivia Vidal', 1, 41).
ligacao('Alberto Estrela', 'Rui Mariske', 1, 47).
ligacao('Alberto Estrela', 'Lisandra Batata', 2, 34).
ligacao('Alberto Estrela', 'Alma Velasco', 3, -4).
ligacao('Alberto Estrela', 'Zavier Salomao', 2, -1).
ligacao('Alberto Estrela', 'Xavier Alcaide', 3, 22).
ligacao('Alberto Estrela', 'Teresa Barbosa', 2, 30).
ligacao('Alberto Estrela', 'Helena Peixoto', 1, 23).
ligacao('Alberto Estrela', 'Telmo Catarino', 2, 13).
ligacao('Alberto Estrela', 'Guilherme Vital', 3, 35).
ligacao('Alberto Estrela', 'Rita Brandao', 2, 31).
ligacao('Alberto Estrela', 'Sara Homem', 1, 20).
ligacao('Alberto Estrela', 'Veronica Colaca', 3, -4).
ligacao('Alberto Estrela', 'Emilia Monforte', 2, 50).
ligacao('Alberto Estrela', 'Olivia Vidal', 2, 11).
ligacao('Alberto Camara', 'Rui Mariske', 3, -4).
ligacao('Alberto Camara', 'Lisandra Batata', 3, 3).
ligacao('Alberto Camara', 'Alma Velasco', 2, 22).
ligacao('Alberto Camara', 'Zavier Salomao', 2, 29).
ligacao('Alberto Camara', 'Xavier Alcaide', 1, 0).
ligacao('Alberto Camara', 'Teresa Barbosa', 2, 11).
ligacao('Alberto Camara', 'Helena Peixoto', 2, 16).
ligacao('Alberto Camara', 'Telmo Catarino', 3, 3).
ligacao('Alberto Camara', 'Guilherme Vital', 1, 35).
ligacao('Alberto Camara', 'Rita Brandao', 2, -4).
ligacao('Alberto Camara', 'Sara Homem', 2, -6).
ligacao('Alberto Camara', 'Veronica Colaca', 3, 25).
ligacao('Alberto Camara', 'Emilia Monforte', 1, 42).
ligacao('Alberto Camara', 'Olivia Vidal', 2, 43).
ligacao('Diana Chaves', 'Rui Mariske', 2, 46).
ligacao('Diana Chaves', 'Lisandra Batata', 3, 11).
ligacao('Diana Chaves', 'Alma Velasco', 1, 30).
ligacao('Diana Chaves', 'Zavier Salomao', 3, 18).
ligacao('Diana Chaves', 'Xavier Alcaide', 3, -5).
ligacao('Diana Chaves', 'Teresa Barbosa', 2, 7).
ligacao('Diana Chaves', 'Helena Peixoto', 3, 14).
ligacao('Diana Chaves', 'Telmo Catarino', 2, 0).
ligacao('Diana Chaves', 'Guilherme Vital', 1, 7).
ligacao('Diana Chaves', 'Rita Brandao', 3, -7).
ligacao('Diana Chaves', 'Sara Homem', 2, 5).
ligacao('Diana Chaves', 'Veronica Colaca', 3, 21).
ligacao('Diana Chaves', 'Emilia Monforte', 2, -9).
ligacao('Diana Chaves', 'Olivia Vidal', 3, 25).
ligacao('Joao Prada', 'Rui Mariske', 3, 41).
ligacao('Joao Prada', 'Lisandra Batata', 1, 16).
ligacao('Joao Prada', 'Alma Velasco', 1, 19).
ligacao('Joao Prada', 'Zavier Salomao', 2, 23).
ligacao('Joao Prada', 'Xavier Alcaide', 2, 16).
ligacao('Joao Prada', 'Teresa Barbosa', 1, 44).
ligacao('Joao Prada', 'Helena Peixoto', 3, 45).
ligacao('Joao Prada', 'Telmo Catarino', 1, 41).
ligacao('Joao Prada', 'Guilherme Vital', 1, 0).
ligacao('Joao Prada', 'Rita Brandao', 1, 50).
ligacao('Joao Prada', 'Sara Homem', 2, 42).
ligacao('Joao Prada', 'Veronica Colaca', 1, -2).
ligacao('Joao Prada', 'Emilia Monforte', 3, 49).
ligacao('Joao Prada', 'Olivia Vidal', 1, 32).
ligacao('Telmo Catarino', 'Rosa Machado', 3, 2).
ligacao('Telmo Catarino', 'Guilherme Araujo', 1, -9).
ligacao('Telmo Catarino', 'Joana Araujo', 2, 45).
ligacao('Telmo Catarino', 'Alberto Estrela', 3, 29).
ligacao('Telmo Catarino', 'Alberto Camara', 1, 12).
ligacao('Telmo Catarino', 'Diana Chaves', 3, 34).
ligacao('Telmo Catarino', 'Joao Prada', 2, 32).
ligacao('Telmo Catarino', 'Maria Francisca', 1, 11).
ligacao('Telmo Catarino', 'Rui Duraes', 3, 47).
ligacao('Telmo Catarino', 'Rui Pedro', 1, -3).
ligacao('Telmo Catarino', 'Alice Monforte', 2, 21).
ligacao('Telmo Catarino', 'Antero Ouro', 2, 34).
ligacao('Telmo Catarino', 'Rafaela Uria', 3, 36).
ligacao('Telmo Catarino', 'Liliana Infante', 1, 15).
ligacao('Guilherme Vital', 'Rosa Machado', 3, 41).
ligacao('Guilherme Vital', 'Guilherme Araujo', 3, -4).
ligacao('Guilherme Vital', 'Joana Araujo', 1, 31).
ligacao('Guilherme Vital', 'Alberto Estrela', 3, 40).
ligacao('Guilherme Vital', 'Alberto Camara', 3, 29).
ligacao('Guilherme Vital', 'Diana Chaves', 1, 30).
ligacao('Guilherme Vital', 'Joao Prada', 1, 18).
ligacao('Guilherme Vital', 'Maria Francisca', 2, 40).
ligacao('Guilherme Vital', 'Rui Duraes', 1, 3).
ligacao('Guilherme Vital', 'Rui Pedro', 2, 16).
ligacao('Guilherme Vital', 'Alice Monforte', 2, 13).
ligacao('Guilherme Vital', 'Antero Ouro', 3, 46).
ligacao('Guilherme Vital', 'Rafaela Uria', 3, 18).
ligacao('Guilherme Vital', 'Liliana Infante', 1, 50).
ligacao('Rita Brandao', 'Rosa Machado', 3, 42).
ligacao('Rita Brandao', 'Guilherme Araujo', 2, 30).
ligacao('Rita Brandao', 'Joana Araujo', 3, 28).
ligacao('Rita Brandao', 'Alberto Estrela', 1, -6).
ligacao('Rita Brandao', 'Alberto Camara', 1, 33).
ligacao('Rita Brandao', 'Diana Chaves', 2, 26).
ligacao('Rita Brandao', 'Joao Prada', 2, -9).
ligacao('Rita Brandao', 'Maria Francisca', 1, 37).
ligacao('Rita Brandao', 'Rui Duraes', 1, 11).
ligacao('Rita Brandao', 'Rui Pedro', 1, 10).
ligacao('Rita Brandao', 'Alice Monforte', 2, 50).
ligacao('Rita Brandao', 'Antero Ouro', 1, -5).
ligacao('Rita Brandao', 'Rafaela Uria', 1, 48).
ligacao('Rita Brandao', 'Liliana Infante', 3, 35).
ligacao('Sara Homem', 'Rosa Machado', 2, 38).
ligacao('Sara Homem', 'Guilherme Araujo', 2, 19).
ligacao('Sara Homem', 'Joana Araujo', 2, 3).
ligacao('Sara Homem', 'Alberto Estrela', 1, 0).
ligacao('Sara Homem', 'Alberto Camara', 2, 38).
ligacao('Sara Homem', 'Diana Chaves', 3, 16).
ligacao('Sara Homem', 'Joao Prada', 1, 12).
ligacao('Sara Homem', 'Maria Francisca', 3, 47).
ligacao('Sara Homem', 'Rui Duraes', 1, 46).
ligacao('Sara Homem', 'Rui Pedro', 2, 23).
ligacao('Sara Homem', 'Alice Monforte', 1, 1).
ligacao('Sara Homem', 'Antero Ouro', 1, 20).
ligacao('Sara Homem', 'Rafaela Uria', 2, 38).
ligacao('Sara Homem', 'Liliana Infante', 3, -10).
ligacao('Veronica Colaca', 'Rosa Machado', 3, 5).
ligacao('Veronica Colaca', 'Guilherme Araujo', 3, 45).
ligacao('Veronica Colaca', 'Joana Araujo', 1, 5).
ligacao('Veronica Colaca', 'Alberto Estrela', 3, 41).
ligacao('Veronica Colaca', 'Alberto Camara', 2, -10).
ligacao('Veronica Colaca', 'Diana Chaves', 3, 37).
ligacao('Veronica Colaca', 'Joao Prada', 1, 41).
ligacao('Veronica Colaca', 'Maria Francisca', 1, 6).
ligacao('Veronica Colaca', 'Rui Duraes', 3, 6).
ligacao('Veronica Colaca', 'Rui Pedro', 3, -10).
ligacao('Veronica Colaca', 'Alice Monforte', 2, 12).
ligacao('Veronica Colaca', 'Antero Ouro', 2, 36).
ligacao('Veronica Colaca', 'Rafaela Uria', 2, 36).
ligacao('Veronica Colaca', 'Liliana Infante', 3, 44).
ligacao('Emilia Monforte', 'Rosa Machado', 3, 15).
ligacao('Emilia Monforte', 'Guilherme Araujo', 1, -4).
ligacao('Emilia Monforte', 'Joana Araujo', 2, -8).
ligacao('Emilia Monforte', 'Alberto Estrela', 2, 43).
ligacao('Emilia Monforte', 'Alberto Camara', 2, 33).
ligacao('Emilia Monforte', 'Diana Chaves', 2, 36).
ligacao('Emilia Monforte', 'Joao Prada', 2, 20).
ligacao('Emilia Monforte', 'Maria Francisca', 1, 27).
ligacao('Emilia Monforte', 'Rui Duraes', 3, 34).
ligacao('Emilia Monforte', 'Rui Pedro', 3, 48).
ligacao('Emilia Monforte', 'Alice Monforte', 3, 19).
ligacao('Emilia Monforte', 'Antero Ouro', 3, 25).
ligacao('Emilia Monforte', 'Rafaela Uria', 3, 47).
ligacao('Emilia Monforte', 'Liliana Infante', 1, -8).
ligacao('Olivia Vidal', 'Rosa Machado', 1, 44).
ligacao('Olivia Vidal', 'Guilherme Araujo', 2, -1).
ligacao('Olivia Vidal', 'Joana Araujo', 3, 47).
ligacao('Olivia Vidal', 'Alberto Estrela', 3, 26).
ligacao('Olivia Vidal', 'Alberto Camara', 2, 37).
ligacao('Olivia Vidal', 'Diana Chaves', 1, 17).
ligacao('Olivia Vidal', 'Joao Prada', 3, 23).
ligacao('Olivia Vidal', 'Maria Francisca', 2, 20).
ligacao('Olivia Vidal', 'Rui Duraes', 1, 14).
ligacao('Olivia Vidal', 'Rui Pedro', 3, 5).
ligacao('Olivia Vidal', 'Alice Monforte', 1, 44).
ligacao('Olivia Vidal', 'Antero Ouro', 2, 42).
ligacao('Olivia Vidal', 'Rafaela Uria', 1, 29).
ligacao('Olivia Vidal', 'Liliana Infante', 3, 26).
ligacao('Maria Francisca', 'Pedro Mourao', 3, 16).
ligacao('Maria Francisca', 'Telmo Catarino', 1, 4).
ligacao('Maria Francisca', 'Guilherme Vital', 3, 16).
ligacao('Maria Francisca', 'Rita Brandao', 1, 35).
ligacao('Maria Francisca', 'Sara Homem', 2, 2).
ligacao('Maria Francisca', 'Veronica Colaca', 2, 34).
ligacao('Maria Francisca', 'Emilia Monforte', 3, 47).
ligacao('Maria Francisca', 'Olivia Vidal', 3, 49).
ligacao('Rui Duraes', 'Pedro Mourao', 2, 2).
ligacao('Rui Duraes', 'Telmo Catarino', 2, 7).
ligacao('Rui Duraes', 'Guilherme Vital', 3, -4).
ligacao('Rui Duraes', 'Rita Brandao', 1, -1).
ligacao('Rui Duraes', 'Sara Homem', 2, 32).
ligacao('Rui Duraes', 'Veronica Colaca', 1, -8).
ligacao('Rui Duraes', 'Emilia Monforte', 1, 31).
ligacao('Rui Duraes', 'Olivia Vidal', 2, 12).
ligacao('Rui Pedro', 'Pedro Mourao', 3, 41).
ligacao('Rui Pedro', 'Telmo Catarino', 1, 45).
ligacao('Rui Pedro', 'Guilherme Vital', 1, 21).
ligacao('Rui Pedro', 'Rita Brandao', 3, 10).
ligacao('Rui Pedro', 'Sara Homem', 2, -10).
ligacao('Rui Pedro', 'Veronica Colaca', 3, 44).
ligacao('Rui Pedro', 'Emilia Monforte', 3, 20).
ligacao('Rui Pedro', 'Olivia Vidal', 1, -7).
ligacao('Alice Monforte', 'Pedro Mourao', 2, 20).
ligacao('Alice Monforte', 'Telmo Catarino', 2, 4).
ligacao('Alice Monforte', 'Guilherme Vital', 3, 33).
ligacao('Alice Monforte', 'Rita Brandao', 3, -7).
ligacao('Alice Monforte', 'Sara Homem', 3, 7).
ligacao('Alice Monforte', 'Veronica Colaca', 1, 19).
ligacao('Alice Monforte', 'Emilia Monforte', 1, 20).
ligacao('Alice Monforte', 'Olivia Vidal', 1, 30).
ligacao('Antero Ouro', 'Pedro Mourao', 1, 18).
ligacao('Antero Ouro', 'Telmo Catarino', 2, 1).
ligacao('Antero Ouro', 'Guilherme Vital', 1, -5).
ligacao('Antero Ouro', 'Rita Brandao', 1, 50).
ligacao('Antero Ouro', 'Sara Homem', 2, 2).
ligacao('Antero Ouro', 'Veronica Colaca', 3, -3).
ligacao('Antero Ouro', 'Emilia Monforte', 2, 28).
ligacao('Antero Ouro', 'Olivia Vidal', 1, 24).
ligacao('Rafaela Uria', 'Pedro Mourao', 2, -6).
ligacao('Rafaela Uria', 'Telmo Catarino', 2, 39).
ligacao('Rafaela Uria', 'Guilherme Vital', 2, 36).
ligacao('Rafaela Uria', 'Rita Brandao', 3, 43).
ligacao('Rafaela Uria', 'Sara Homem', 1, 34).
ligacao('Rafaela Uria', 'Veronica Colaca', 1, 26).
ligacao('Rafaela Uria', 'Emilia Monforte', 1, 38).
ligacao('Rafaela Uria', 'Olivia Vidal', 2, 2).
ligacao('Liliana Infante', 'Pedro Mourao', 3, 5).
ligacao('Liliana Infante', 'Telmo Catarino', 3, 45).
ligacao('Liliana Infante', 'Guilherme Vital', 3, -7).
ligacao('Liliana Infante', 'Rita Brandao', 2, 29).
ligacao('Liliana Infante', 'Sara Homem', 2, 47).
ligacao('Liliana Infante', 'Veronica Colaca', 1, 33).
ligacao('Liliana Infante', 'Emilia Monforte', 3, 49).
ligacao('Liliana Infante', 'Olivia Vidal', 1, 2).
