%------------------
% CONNECTIONS
%------------------


% parameters:
%	User 1
%	User 2
%	Connection strengh
%		- 1: Colleagues
%		- 2: Friends
%		- 3: Family
%	Connection Tag


%--------------------------------


:-dynamic ligacao/4.

%ligacao('Sarah Silva', 'Pedro Mourao',2,31).
%ligacao('Pedro Mourao', 'Sarah Silva',3,11).

ligacao('Sarah Silva', 'Rafael Soares', 3, -43).
ligacao('Sarah Silva', 'Dario Ornelas', 3, 4).
ligacao('Sarah Silva', 'Yuri Serralheiro', 3, 25).
ligacao('Sarah Silva', 'Francisco Vilar', 3, 11).
ligacao('Sarah Silva', 'Nancy Sodre', 3, 14).
ligacao('Sarah Silva', 'David Correia', 1, 24).
ligacao('Sarah Silva', 'Flora Quental', 3, 22).
ligacao('Sarah Silva', 'Lidia Silva', 3, 35).
ligacao('Sarah Silva', 'Cesar Leite', 3, 28).
ligacao('Pedro Mourao', 'Antonio Pedro', 3, 30).
ligacao('Pedro Mourao', 'Alma Braga', 1, 16).
ligacao('Pedro Mourao', 'Manuela Martinho', 2, 30).
ligacao('Pedro Mourao', 'Briana Toste', 3, 50).
ligacao('Pedro Mourao', 'Raquel Valverde', 1, 48).
ligacao('Pedro Mourao', 'Liana canela', 1, -4).
ligacao('Pedro Mourao', 'Sara Basilio', 1, 43).
ligacao('Pedro Mourao', 'Josefina Lamego', 3, 41).
ligacao('Pedro Mourao', 'Janice Adao', 3, 26).
ligacao('Rafael Soares', 'Sarah Silva', 1, 7).
ligacao('Rafael Soares', 'Fabio Silva', 2, 23).
ligacao('Rafael Soares', 'Jonatas Granjeiro', 2, 10).
ligacao('Rafael Soares', 'Marco Gravato', 1, 19).
ligacao('Rafael Soares', 'Denzel Rufino', 2, 8).
ligacao('Rafael Soares', 'Joao Bulhosa', 2, -6).
ligacao('Rafael Soares', 'Ana Camarinho', 1, 48).
ligacao('Rafael Soares', 'Mia Carvalho', 1, 24).
ligacao('Rafael Soares', 'Marcos Vieira', 1, 3).
ligacao('Rafael Soares', 'Vanessa Carvalho', 3, 36).
ligacao('Dario Ornelas', 'Sarah Silva', 3, -8).
ligacao('Dario Ornelas', 'Fabio Silva', 2, 47).
ligacao('Dario Ornelas', 'Jonatas Granjeiro', 1, 28).
ligacao('Dario Ornelas', 'Marco Gravato', 2, 46).
ligacao('Dario Ornelas', 'Denzel Rufino', 3, 17).
ligacao('Dario Ornelas', 'Joao Bulhosa', 1, -10).
ligacao('Dario Ornelas', 'Ana Camarinho', 1, 19).
ligacao('Dario Ornelas', 'Mia Carvalho', 2, 49).
ligacao('Dario Ornelas', 'Marcos Vieira', 2, 19).
ligacao('Dario Ornelas', 'Vanessa Carvalho', 2, 18).
ligacao('Yuri Serralheiro', 'Sarah Silva', 2, -10).
ligacao('Yuri Serralheiro', 'Fabio Silva', 2, 27).
ligacao('Yuri Serralheiro', 'Jonatas Granjeiro', 1, -7).
ligacao('Yuri Serralheiro', 'Marco Gravato', 3, 0).
ligacao('Yuri Serralheiro', 'Denzel Rufino', 1, 38).
ligacao('Yuri Serralheiro', 'Joao Bulhosa', 2, 0).
ligacao('Yuri Serralheiro', 'Ana Camarinho', 1, 32).
ligacao('Yuri Serralheiro', 'Mia Carvalho', 3, 19).
ligacao('Yuri Serralheiro', 'Marcos Vieira', 3, 40).
ligacao('Yuri Serralheiro', 'Vanessa Carvalho', 3, 2).
ligacao('Francisco Vilar', 'Sarah Silva', 3, 16).
ligacao('Francisco Vilar', 'Fabio Silva', 2, -4).
ligacao('Francisco Vilar', 'Jonatas Granjeiro', 3, 9).
ligacao('Francisco Vilar', 'Marco Gravato', 3, -1).
ligacao('Francisco Vilar', 'Denzel Rufino', 1, 7).
ligacao('Francisco Vilar', 'Joao Bulhosa', 3, -9).
ligacao('Francisco Vilar', 'Ana Camarinho', 3, 31).
ligacao('Francisco Vilar', 'Mia Carvalho', 1, 21).
ligacao('Francisco Vilar', 'Marcos Vieira', 1, 42).
ligacao('Francisco Vilar', 'Vanessa Carvalho', 1, 25).
ligacao('Nancy Sodre', 'Sarah Silva', 2, 10).
ligacao('Nancy Sodre', 'Fabio Silva', 1, 41).
ligacao('Nancy Sodre', 'Jonatas Granjeiro', 3, 31).
ligacao('Nancy Sodre', 'Marco Gravato', 1, 44).
ligacao('Nancy Sodre', 'Denzel Rufino', 2, 1).
ligacao('Nancy Sodre', 'Joao Bulhosa', 1, 34).
ligacao('Nancy Sodre', 'Ana Camarinho', 3, 25).
ligacao('Nancy Sodre', 'Mia Carvalho', 1, 21).
ligacao('Nancy Sodre', 'Marcos Vieira', 3, 47).
ligacao('Nancy Sodre', 'Vanessa Carvalho', 3, 8).
ligacao('David Correia', 'Sarah Silva', 1, 28).
ligacao('David Correia', 'Fabio Silva', 1, 22).
ligacao('David Correia', 'Jonatas Granjeiro', 3, -6).
ligacao('David Correia', 'Marco Gravato', 2, 12).
ligacao('David Correia', 'Denzel Rufino', 3, 46).
ligacao('David Correia', 'Joao Bulhosa', 2, -8).
ligacao('David Correia', 'Ana Camarinho', 1, 32).
ligacao('David Correia', 'Mia Carvalho', 3, 49).
ligacao('David Correia', 'Marcos Vieira', 2, 47).
ligacao('David Correia', 'Vanessa Carvalho', 2, 33).
ligacao('Flora Quental', 'Sarah Silva', 3, 3).
ligacao('Flora Quental', 'Fabio Silva', 3, -8).
ligacao('Flora Quental', 'Jonatas Granjeiro', 1, 38).
ligacao('Flora Quental', 'Marco Gravato', 2, -4).
ligacao('Flora Quental', 'Denzel Rufino', 1, 15).
ligacao('Flora Quental', 'Joao Bulhosa', 2, 41).
ligacao('Flora Quental', 'Ana Camarinho', 2, 39).
ligacao('Flora Quental', 'Mia Carvalho', 1, 14).
ligacao('Flora Quental', 'Marcos Vieira', 1, 31).
ligacao('Flora Quental', 'Vanessa Carvalho', 3, -10).
ligacao('Lidia Silva', 'Sarah Silva', 3, 27).
ligacao('Lidia Silva', 'Fabio Silva', 3, 34).
ligacao('Lidia Silva', 'Jonatas Granjeiro', 2, 6).
ligacao('Lidia Silva', 'Marco Gravato', 1, 11).
ligacao('Lidia Silva', 'Denzel Rufino', 3, 35).
ligacao('Lidia Silva', 'Joao Bulhosa', 3, 33).
ligacao('Lidia Silva', 'Ana Camarinho', 1, 46).
ligacao('Lidia Silva', 'Mia Carvalho', 1, 40).
ligacao('Lidia Silva', 'Marcos Vieira', 3, 29).
ligacao('Lidia Silva', 'Vanessa Carvalho', 2, 30).
ligacao('Cesar Leite', 'Sarah Silva', 2, 16).
ligacao('Cesar Leite', 'Fabio Silva', 2, 48).
ligacao('Cesar Leite', 'Jonatas Granjeiro', 1, 26).
ligacao('Cesar Leite', 'Marco Gravato', 3, 44).
ligacao('Cesar Leite', 'Denzel Rufino', 2, 50).
ligacao('Cesar Leite', 'Joao Bulhosa', 3, 9).
ligacao('Cesar Leite', 'Ana Camarinho', 2, 3).
ligacao('Cesar Leite', 'Mia Carvalho', 2, 40).
ligacao('Cesar Leite', 'Marcos Vieira', 3, -6).
ligacao('Cesar Leite', 'Vanessa Carvalho', 1, 46).
ligacao('Fabio Silva', 'Rafael Soares', 1, 5).
ligacao('Fabio Silva', 'Dario Ornelas', 2, 23).
ligacao('Fabio Silva', 'Yuri Serralheiro', 1, 24).
ligacao('Fabio Silva', 'Francisco Vilar', 1, 45).
ligacao('Fabio Silva', 'Nancy Sodre', 2, 10).
ligacao('Fabio Silva', 'David Correia', 3, 34).
ligacao('Fabio Silva', 'Flora Quental', 3, 18).
ligacao('Fabio Silva', 'Lidia Silva', 1, 28).
ligacao('Fabio Silva', 'Cesar Leite', 2, -8).
ligacao('Fabio Silva', 'Carlos Moutinho', 1, 31).
ligacao('Fabio Silva', 'Breno Granja', 3, 13).
ligacao('Fabio Silva', 'Rodrigo Sousa', 3, 47).
ligacao('Fabio Silva', 'Andreia Sousa', 3, 35).
ligacao('Fabio Silva', 'Deolinda Varzeas', 3, 40).
ligacao('Fabio Silva', 'Beatriz Varzeas', 1, 20).
ligacao('Fabio Silva', 'Antonio Morais', 3, 6).
ligacao('Fabio Silva', 'Aurea Monsanto', 2, 15).
ligacao('Fabio Silva', 'Isabel Leite', 3, 41).
ligacao('Jonatas Granjeiro', 'Rafael Soares', 2, 41).
ligacao('Jonatas Granjeiro', 'Dario Ornelas', 1, 8).
ligacao('Jonatas Granjeiro', 'Yuri Serralheiro', 3, -3).
ligacao('Jonatas Granjeiro', 'Francisco Vilar', 1, 50).
ligacao('Jonatas Granjeiro', 'Nancy Sodre', 2, 38).
ligacao('Jonatas Granjeiro', 'David Correia', 2, 0).
ligacao('Jonatas Granjeiro', 'Flora Quental', 2, 18).
ligacao('Jonatas Granjeiro', 'Lidia Silva', 1, 10).
ligacao('Jonatas Granjeiro', 'Cesar Leite', 1, 32).
ligacao('Jonatas Granjeiro', 'Carlos Moutinho', 1, 11).
ligacao('Jonatas Granjeiro', 'Breno Granja', 3, 46).
ligacao('Jonatas Granjeiro', 'Rodrigo Sousa', 1, 45).
ligacao('Jonatas Granjeiro', 'Andreia Sousa', 2, 30).
ligacao('Jonatas Granjeiro', 'Deolinda Varzeas', 2, 30).
ligacao('Jonatas Granjeiro', 'Beatriz Varzeas', 2, 15).
ligacao('Jonatas Granjeiro', 'Antonio Morais', 1, -4).
ligacao('Jonatas Granjeiro', 'Aurea Monsanto', 3, -3).
ligacao('Jonatas Granjeiro', 'Isabel Leite', 3, 37).
ligacao('Marco Gravato', 'Rafael Soares', 3, 23).
ligacao('Marco Gravato', 'Dario Ornelas', 3, 12).
ligacao('Marco Gravato', 'Yuri Serralheiro', 1, 14).
ligacao('Marco Gravato', 'Francisco Vilar', 2, -3).
ligacao('Marco Gravato', 'Nancy Sodre', 2, 22).
ligacao('Marco Gravato', 'David Correia', 2, 1).
ligacao('Marco Gravato', 'Flora Quental', 3, 29).
ligacao('Marco Gravato', 'Lidia Silva', 1, 50).
ligacao('Marco Gravato', 'Cesar Leite', 3, 21).
ligacao('Marco Gravato', 'Carlos Moutinho', 3, 0).
ligacao('Marco Gravato', 'Breno Granja', 3, 13).
ligacao('Marco Gravato', 'Rodrigo Sousa', 1, 26).
ligacao('Marco Gravato', 'Andreia Sousa', 2, 33).
ligacao('Marco Gravato', 'Deolinda Varzeas', 1, 44).
ligacao('Marco Gravato', 'Beatriz Varzeas', 2, 24).
ligacao('Marco Gravato', 'Antonio Morais', 3, 23).
ligacao('Marco Gravato', 'Aurea Monsanto', 1, 15).
ligacao('Marco Gravato', 'Isabel Leite', 1, 48).
ligacao('Denzel Rufino', 'Rafael Soares', 2, 13).
ligacao('Denzel Rufino', 'Dario Ornelas', 2, -8).
ligacao('Denzel Rufino', 'Yuri Serralheiro', 3, 25).
ligacao('Denzel Rufino', 'Francisco Vilar', 1, 25).
ligacao('Denzel Rufino', 'Nancy Sodre', 2, 4).
ligacao('Denzel Rufino', 'David Correia', 3, 42).
ligacao('Denzel Rufino', 'Flora Quental', 3, 4).
ligacao('Denzel Rufino', 'Lidia Silva', 1, 5).
ligacao('Denzel Rufino', 'Cesar Leite', 3, 30).
ligacao('Denzel Rufino', 'Carlos Moutinho', 2, 29).
ligacao('Denzel Rufino', 'Breno Granja', 3, 15).
ligacao('Denzel Rufino', 'Rodrigo Sousa', 3, 45).
ligacao('Denzel Rufino', 'Andreia Sousa', 1, 30).
ligacao('Denzel Rufino', 'Deolinda Varzeas', 1, 27).
ligacao('Denzel Rufino', 'Beatriz Varzeas', 3, 11).
ligacao('Denzel Rufino', 'Antonio Morais', 2, 42).
ligacao('Denzel Rufino', 'Aurea Monsanto', 1, 28).
ligacao('Denzel Rufino', 'Isabel Leite', 2, 47).
ligacao('Joao Bulhosa', 'Rafael Soares', 2, -1).
ligacao('Joao Bulhosa', 'Dario Ornelas', 1, 31).
ligacao('Joao Bulhosa', 'Yuri Serralheiro', 2, 3).
ligacao('Joao Bulhosa', 'Francisco Vilar', 1, 30).
ligacao('Joao Bulhosa', 'Nancy Sodre', 1, 17).
ligacao('Joao Bulhosa', 'David Correia', 2, 21).
ligacao('Joao Bulhosa', 'Flora Quental', 3, -10).
ligacao('Joao Bulhosa', 'Lidia Silva', 3, 20).
ligacao('Joao Bulhosa', 'Cesar Leite', 3, 4).
ligacao('Joao Bulhosa', 'Carlos Moutinho', 3, 38).
ligacao('Joao Bulhosa', 'Breno Granja', 1, -4).
ligacao('Joao Bulhosa', 'Rodrigo Sousa', 3, 45).
ligacao('Joao Bulhosa', 'Andreia Sousa', 3, 14).
ligacao('Joao Bulhosa', 'Deolinda Varzeas', 1, -1).
ligacao('Joao Bulhosa', 'Beatriz Varzeas', 3, 18).
ligacao('Joao Bulhosa', 'Antonio Morais', 2, 1).
ligacao('Joao Bulhosa', 'Aurea Monsanto', 2, 24).
ligacao('Joao Bulhosa', 'Isabel Leite', 3, -8).
ligacao('Ana Camarinho', 'Rafael Soares', 1, 45).
ligacao('Ana Camarinho', 'Dario Ornelas', 1, -10).
ligacao('Ana Camarinho', 'Yuri Serralheiro', 2, 48).
ligacao('Ana Camarinho', 'Francisco Vilar', 3, 27).
ligacao('Ana Camarinho', 'Nancy Sodre', 1, 12).
ligacao('Ana Camarinho', 'David Correia', 1, 23).
ligacao('Ana Camarinho', 'Flora Quental', 1, 24).
ligacao('Ana Camarinho', 'Lidia Silva', 2, 9).
ligacao('Ana Camarinho', 'Cesar Leite', 2, 39).
ligacao('Ana Camarinho', 'Carlos Moutinho', 2, 5).
ligacao('Ana Camarinho', 'Breno Granja', 2, -3).
ligacao('Ana Camarinho', 'Rodrigo Sousa', 3, 28).
ligacao('Ana Camarinho', 'Andreia Sousa', 2, 9).
ligacao('Ana Camarinho', 'Deolinda Varzeas', 1, -10).
ligacao('Ana Camarinho', 'Beatriz Varzeas', 3, 5).
ligacao('Ana Camarinho', 'Antonio Morais', 3, 1).
ligacao('Ana Camarinho', 'Aurea Monsanto', 1, 33).
ligacao('Ana Camarinho', 'Isabel Leite', 1, 39).
ligacao('Mia Carvalho', 'Rafael Soares', 2, 45).
ligacao('Mia Carvalho', 'Dario Ornelas', 1, 32).
ligacao('Mia Carvalho', 'Yuri Serralheiro', 2, 12).
ligacao('Mia Carvalho', 'Francisco Vilar', 1, 45).
ligacao('Mia Carvalho', 'Nancy Sodre', 1, 13).
ligacao('Mia Carvalho', 'David Correia', 1, 30).
ligacao('Mia Carvalho', 'Flora Quental', 1, -6).
ligacao('Mia Carvalho', 'Lidia Silva', 3, 10).
ligacao('Mia Carvalho', 'Cesar Leite', 3, 40).
ligacao('Mia Carvalho', 'Carlos Moutinho', 3, 40).
ligacao('Mia Carvalho', 'Breno Granja', 3, -9).
ligacao('Mia Carvalho', 'Rodrigo Sousa', 3, 4).
ligacao('Mia Carvalho', 'Andreia Sousa', 1, 32).
ligacao('Mia Carvalho', 'Deolinda Varzeas', 1, -3).
ligacao('Mia Carvalho', 'Beatriz Varzeas', 1, 43).
ligacao('Mia Carvalho', 'Antonio Morais', 3, 24).
ligacao('Mia Carvalho', 'Aurea Monsanto', 1, 24).
ligacao('Mia Carvalho', 'Isabel Leite', 3, 36).
ligacao('Marcos Vieira', 'Rafael Soares', 1, 34).
ligacao('Marcos Vieira', 'Dario Ornelas', 2, 40).
ligacao('Marcos Vieira', 'Yuri Serralheiro', 3, 37).
ligacao('Marcos Vieira', 'Francisco Vilar', 1, 40).
ligacao('Marcos Vieira', 'Nancy Sodre', 3, 49).
ligacao('Marcos Vieira', 'David Correia', 3, 14).
ligacao('Marcos Vieira', 'Flora Quental', 2, 16).
ligacao('Marcos Vieira', 'Lidia Silva', 1, 49).
ligacao('Marcos Vieira', 'Cesar Leite', 1, 31).
ligacao('Marcos Vieira', 'Carlos Moutinho', 1, 27).
ligacao('Marcos Vieira', 'Breno Granja', 2, 8).
ligacao('Marcos Vieira', 'Rodrigo Sousa', 1, 32).
ligacao('Marcos Vieira', 'Andreia Sousa', 2, 48).
ligacao('Marcos Vieira', 'Deolinda Varzeas', 2, 50).
ligacao('Marcos Vieira', 'Beatriz Varzeas', 3, 47).
ligacao('Marcos Vieira', 'Antonio Morais', 3, 6).
ligacao('Marcos Vieira', 'Aurea Monsanto', 3, -6).
ligacao('Marcos Vieira', 'Isabel Leite', 3, -9).
ligacao('Vanessa Carvalho', 'Rafael Soares', 2, 14).
ligacao('Vanessa Carvalho', 'Dario Ornelas', 1, 26).
ligacao('Vanessa Carvalho', 'Yuri Serralheiro', 2, 50).
ligacao('Vanessa Carvalho', 'Francisco Vilar', 3, -5).
ligacao('Vanessa Carvalho', 'Nancy Sodre', 3, 33).
ligacao('Vanessa Carvalho', 'David Correia', 2, 40).
ligacao('Vanessa Carvalho', 'Flora Quental', 1, 36).
ligacao('Vanessa Carvalho', 'Lidia Silva', 2, -6).
ligacao('Vanessa Carvalho', 'Cesar Leite', 2, 48).
ligacao('Vanessa Carvalho', 'Carlos Moutinho', 2, 25).
ligacao('Vanessa Carvalho', 'Breno Granja', 1, 27).
ligacao('Vanessa Carvalho', 'Rodrigo Sousa', 1, 2).
ligacao('Vanessa Carvalho', 'Andreia Sousa', 1, 50).
ligacao('Vanessa Carvalho', 'Deolinda Varzeas', 3, -6).
ligacao('Vanessa Carvalho', 'Beatriz Varzeas', 1, 10).
ligacao('Vanessa Carvalho', 'Antonio Morais', 3, -2).
ligacao('Vanessa Carvalho', 'Aurea Monsanto', 3, 36).
ligacao('Vanessa Carvalho', 'Isabel Leite', 1, -7).
ligacao('Carlos Moutinho', 'Fabio Silva', 2, 27).
ligacao('Carlos Moutinho', 'Jonatas Granjeiro', 2, 32).
ligacao('Carlos Moutinho', 'Marco Gravato', 3, 16).
ligacao('Carlos Moutinho', 'Denzel Rufino', 3, 35).
ligacao('Carlos Moutinho', 'Joao Bulhosa', 3, 13).
ligacao('Carlos Moutinho', 'Ana Camarinho', 1, 44).
ligacao('Carlos Moutinho', 'Mia Carvalho', 3, 25).
ligacao('Carlos Moutinho', 'Marcos Vieira', 3, 11).
ligacao('Carlos Moutinho', 'Vanessa Carvalho', 2, -4).
ligacao('Carlos Moutinho', 'Rui Mariske', 3, 48).
ligacao('Carlos Moutinho', 'Lisandra Batata', 1, 6).
ligacao('Carlos Moutinho', 'Alma Velasco', 3, 47).
ligacao('Carlos Moutinho', 'Zavier Salomao', 3, 16).
ligacao('Carlos Moutinho', 'Xavier Alcaide', 3, 41).
ligacao('Carlos Moutinho', 'Teresa Barbosa', 2, 43).
ligacao('Carlos Moutinho', 'Helena Peixoto', 1, 42).
ligacao('Carlos Moutinho', 'Helena Sousa', 2, 7).
ligacao('Carlos Moutinho', 'Soraia Couto', 3, -6).
ligacao('Breno Granja', 'Fabio Silva', 3, -6).
ligacao('Breno Granja', 'Jonatas Granjeiro', 1, -9).
ligacao('Breno Granja', 'Marco Gravato', 2, 46).
ligacao('Breno Granja', 'Denzel Rufino', 1, 46).
ligacao('Breno Granja', 'Joao Bulhosa', 2, 13).
ligacao('Breno Granja', 'Ana Camarinho', 1, 31).
ligacao('Breno Granja', 'Mia Carvalho', 2, 8).
ligacao('Breno Granja', 'Marcos Vieira', 1, -3).
ligacao('Breno Granja', 'Vanessa Carvalho', 1, 19).
ligacao('Breno Granja', 'Rui Mariske', 3, 20).
ligacao('Breno Granja', 'Lisandra Batata', 3, -1).
ligacao('Breno Granja', 'Alma Velasco', 1, 3).
ligacao('Breno Granja', 'Zavier Salomao', 3, 1).
ligacao('Breno Granja', 'Xavier Alcaide', 1, 23).
ligacao('Breno Granja', 'Teresa Barbosa', 2, -8).
ligacao('Breno Granja', 'Helena Peixoto', 2, 5).
ligacao('Breno Granja', 'Helena Sousa', 3, 47).
ligacao('Breno Granja', 'Soraia Couto', 1, 7).
ligacao('Rodrigo Sousa', 'Fabio Silva', 3, 22).
ligacao('Rodrigo Sousa', 'Jonatas Granjeiro', 3, 11).
ligacao('Rodrigo Sousa', 'Marco Gravato', 1, 44).
ligacao('Rodrigo Sousa', 'Denzel Rufino', 2, 15).
ligacao('Rodrigo Sousa', 'Joao Bulhosa', 2, 38).
ligacao('Rodrigo Sousa', 'Ana Camarinho', 2, 14).
ligacao('Rodrigo Sousa', 'Mia Carvalho', 3, -3).
ligacao('Rodrigo Sousa', 'Marcos Vieira', 2, 0).
ligacao('Rodrigo Sousa', 'Vanessa Carvalho', 1, 18).
ligacao('Rodrigo Sousa', 'Rui Mariske', 3, -4).
ligacao('Rodrigo Sousa', 'Lisandra Batata', 2, 23).
ligacao('Rodrigo Sousa', 'Alma Velasco', 1, -3).
ligacao('Rodrigo Sousa', 'Zavier Salomao', 2, 1).
ligacao('Rodrigo Sousa', 'Xavier Alcaide', 1, -3).
ligacao('Rodrigo Sousa', 'Teresa Barbosa', 2, 47).
ligacao('Rodrigo Sousa', 'Helena Peixoto', 2, 12).
ligacao('Rodrigo Sousa', 'Helena Sousa', 1, -6).
ligacao('Rodrigo Sousa', 'Soraia Couto', 1, 49).
ligacao('Andreia Sousa', 'Fabio Silva', 2, 22).
ligacao('Andreia Sousa', 'Jonatas Granjeiro', 3, 0).
ligacao('Andreia Sousa', 'Marco Gravato', 3, 35).
ligacao('Andreia Sousa', 'Denzel Rufino', 3, 8).
ligacao('Andreia Sousa', 'Joao Bulhosa', 1, 28).
ligacao('Andreia Sousa', 'Ana Camarinho', 1, 4).
ligacao('Andreia Sousa', 'Mia Carvalho', 2, 3).
ligacao('Andreia Sousa', 'Marcos Vieira', 1, 27).
ligacao('Andreia Sousa', 'Vanessa Carvalho', 2, 45).
ligacao('Andreia Sousa', 'Rui Mariske', 2, 20).
ligacao('Andreia Sousa', 'Lisandra Batata', 2, -6).
ligacao('Andreia Sousa', 'Alma Velasco', 1, -10).
ligacao('Andreia Sousa', 'Zavier Salomao', 1, 3).
ligacao('Andreia Sousa', 'Xavier Alcaide', 1, 46).
ligacao('Andreia Sousa', 'Teresa Barbosa', 2, 5).
ligacao('Andreia Sousa', 'Helena Peixoto', 1, 4).
ligacao('Andreia Sousa', 'Helena Sousa', 2, -4).
ligacao('Andreia Sousa', 'Soraia Couto', 3, 34).
ligacao('Deolinda Varzeas', 'Fabio Silva', 2, 21).
ligacao('Deolinda Varzeas', 'Jonatas Granjeiro', 1, 18).
ligacao('Deolinda Varzeas', 'Marco Gravato', 1, -6).
ligacao('Deolinda Varzeas', 'Denzel Rufino', 2, 48).
ligacao('Deolinda Varzeas', 'Joao Bulhosa', 3, 27).
ligacao('Deolinda Varzeas', 'Ana Camarinho', 2, -8).
ligacao('Deolinda Varzeas', 'Mia Carvalho', 2, 23).
ligacao('Deolinda Varzeas', 'Marcos Vieira', 2, 43).
ligacao('Deolinda Varzeas', 'Vanessa Carvalho', 3, 28).
ligacao('Deolinda Varzeas', 'Rui Mariske', 3, 36).
ligacao('Deolinda Varzeas', 'Lisandra Batata', 3, 0).
ligacao('Deolinda Varzeas', 'Alma Velasco', 1, 18).
ligacao('Deolinda Varzeas', 'Zavier Salomao', 1, 45).
ligacao('Deolinda Varzeas', 'Xavier Alcaide', 1, 47).
ligacao('Deolinda Varzeas', 'Teresa Barbosa', 1, -10).
ligacao('Deolinda Varzeas', 'Helena Peixoto', 2, 40).
ligacao('Deolinda Varzeas', 'Helena Sousa', 3, 48).
ligacao('Deolinda Varzeas', 'Soraia Couto', 3, -9).
ligacao('Beatriz Varzeas', 'Fabio Silva', 3, 9).
ligacao('Beatriz Varzeas', 'Jonatas Granjeiro', 3, 19).
ligacao('Beatriz Varzeas', 'Marco Gravato', 2, 5).
ligacao('Beatriz Varzeas', 'Denzel Rufino', 2, 19).
ligacao('Beatriz Varzeas', 'Joao Bulhosa', 2, -4).
ligacao('Beatriz Varzeas', 'Ana Camarinho', 3, 38).
ligacao('Beatriz Varzeas', 'Mia Carvalho', 1, 35).
ligacao('Beatriz Varzeas', 'Marcos Vieira', 2, 29).
ligacao('Beatriz Varzeas', 'Vanessa Carvalho', 3, 48).
ligacao('Beatriz Varzeas', 'Rui Mariske', 3, 17).
ligacao('Beatriz Varzeas', 'Lisandra Batata', 1, 49).
ligacao('Beatriz Varzeas', 'Alma Velasco', 2, 12).
ligacao('Beatriz Varzeas', 'Zavier Salomao', 3, 17).
ligacao('Beatriz Varzeas', 'Xavier Alcaide', 2, 47).
ligacao('Beatriz Varzeas', 'Teresa Barbosa', 3, 50).
ligacao('Beatriz Varzeas', 'Helena Peixoto', 2, 37).
ligacao('Beatriz Varzeas', 'Helena Sousa', 2, 1).
ligacao('Beatriz Varzeas', 'Soraia Couto', 1, 35).
ligacao('Antonio Morais', 'Fabio Silva', 1, 5).
ligacao('Antonio Morais', 'Jonatas Granjeiro', 2, 38).
ligacao('Antonio Morais', 'Marco Gravato', 2, 18).
ligacao('Antonio Morais', 'Denzel Rufino', 1, -7).
ligacao('Antonio Morais', 'Joao Bulhosa', 1, -9).
ligacao('Antonio Morais', 'Ana Camarinho', 2, 36).
ligacao('Antonio Morais', 'Mia Carvalho', 3, 0).
ligacao('Antonio Morais', 'Marcos Vieira', 1, 27).
ligacao('Antonio Morais', 'Vanessa Carvalho', 2, 29).
ligacao('Antonio Morais', 'Rui Mariske', 3, -5).
ligacao('Antonio Morais', 'Lisandra Batata', 2, 25).
ligacao('Antonio Morais', 'Alma Velasco', 3, 42).
ligacao('Antonio Morais', 'Zavier Salomao', 2, 22).
ligacao('Antonio Morais', 'Xavier Alcaide', 3, 45).
ligacao('Antonio Morais', 'Teresa Barbosa', 3, 49).
ligacao('Antonio Morais', 'Helena Peixoto', 2, 38).
ligacao('Antonio Morais', 'Helena Sousa', 1, 9).
ligacao('Antonio Morais', 'Soraia Couto', 2, 15).
ligacao('Aurea Monsanto', 'Fabio Silva', 1, 31).
ligacao('Aurea Monsanto', 'Jonatas Granjeiro', 1, 45).
ligacao('Aurea Monsanto', 'Marco Gravato', 1, 25).
ligacao('Aurea Monsanto', 'Denzel Rufino', 1, 10).
ligacao('Aurea Monsanto', 'Joao Bulhosa', 1, 43).
ligacao('Aurea Monsanto', 'Ana Camarinho', 2, -10).
ligacao('Aurea Monsanto', 'Mia Carvalho', 1, 15).
ligacao('Aurea Monsanto', 'Marcos Vieira', 1, 29).
ligacao('Aurea Monsanto', 'Vanessa Carvalho', 3, 18).
ligacao('Aurea Monsanto', 'Rui Mariske', 1, 20).
ligacao('Aurea Monsanto', 'Lisandra Batata', 3, 48).
ligacao('Aurea Monsanto', 'Alma Velasco', 2, 16).
ligacao('Aurea Monsanto', 'Zavier Salomao', 1, 39).
ligacao('Aurea Monsanto', 'Xavier Alcaide', 1, 23).
ligacao('Aurea Monsanto', 'Teresa Barbosa', 3, 35).
ligacao('Aurea Monsanto', 'Helena Peixoto', 2, -10).
ligacao('Aurea Monsanto', 'Helena Sousa', 2, -5).
ligacao('Aurea Monsanto', 'Soraia Couto', 1, 22).
ligacao('Isabel Leite', 'Fabio Silva', 2, 26).
ligacao('Isabel Leite', 'Jonatas Granjeiro', 2, 12).
ligacao('Isabel Leite', 'Marco Gravato', 3, 5).
ligacao('Isabel Leite', 'Denzel Rufino', 2, -7).
ligacao('Isabel Leite', 'Joao Bulhosa', 1, 5).
ligacao('Isabel Leite', 'Ana Camarinho', 3, 36).
ligacao('Isabel Leite', 'Mia Carvalho', 3, 42).
ligacao('Isabel Leite', 'Marcos Vieira', 2, 34).
ligacao('Isabel Leite', 'Vanessa Carvalho', 2, 8).
ligacao('Isabel Leite', 'Rui Mariske', 3, 25).
ligacao('Isabel Leite', 'Lisandra Batata', 1, 15).
ligacao('Isabel Leite', 'Alma Velasco', 1, -7).
ligacao('Isabel Leite', 'Zavier Salomao', 3, 30).
ligacao('Isabel Leite', 'Xavier Alcaide', 1, 39).
ligacao('Isabel Leite', 'Teresa Barbosa', 3, 38).
ligacao('Isabel Leite', 'Helena Peixoto', 3, 3).
ligacao('Isabel Leite', 'Helena Sousa', 1, -2).
ligacao('Isabel Leite', 'Soraia Couto', 1, 23).
ligacao('Rui Mariske', 'Carlos Moutinho', 1, -10).
ligacao('Rui Mariske', 'Breno Granja', 1, -7).
ligacao('Rui Mariske', 'Rodrigo Sousa', 3, 43).
ligacao('Rui Mariske', 'Andreia Sousa', 1, 7).
ligacao('Rui Mariske', 'Deolinda Varzeas', 2, 39).
ligacao('Rui Mariske', 'Beatriz Varzeas', 3, 15).
ligacao('Rui Mariske', 'Antonio Morais', 1, 21).
ligacao('Rui Mariske', 'Aurea Monsanto', 3, 8).
ligacao('Rui Mariske', 'Isabel Leite', 2, -8).
ligacao('Rui Mariske', 'Rosa Machado', 1, 29).
ligacao('Rui Mariske', 'Guilherme Araujo', 3, 18).
ligacao('Rui Mariske', 'Joana Araujo', 1, 41).
ligacao('Rui Mariske', 'Alberto Estrela', 1, 47).
ligacao('Rui Mariske', 'Alberto Camara', 1, -7).
ligacao('Rui Mariske', 'Diana Chaves', 3, 9).
ligacao('Rui Mariske', 'Joao Prada', 2, 3).
ligacao('Rui Mariske', 'Joao Medina', 2, -4).
ligacao('Rui Mariske', 'Pilar Ouro', 2, 13).
ligacao('Lisandra Batata', 'Carlos Moutinho', 3, 10).
ligacao('Lisandra Batata', 'Breno Granja', 2, 6).
ligacao('Lisandra Batata', 'Rodrigo Sousa', 3, 4).
ligacao('Lisandra Batata', 'Andreia Sousa', 2, 1).
ligacao('Lisandra Batata', 'Deolinda Varzeas', 2, 40).
ligacao('Lisandra Batata', 'Beatriz Varzeas', 1, 47).
ligacao('Lisandra Batata', 'Antonio Morais', 3, 31).
ligacao('Lisandra Batata', 'Aurea Monsanto', 3, 32).
ligacao('Lisandra Batata', 'Isabel Leite', 2, 28).
ligacao('Lisandra Batata', 'Rosa Machado', 1, 27).
ligacao('Lisandra Batata', 'Guilherme Araujo', 2, 35).
ligacao('Lisandra Batata', 'Joana Araujo', 3, 32).
ligacao('Lisandra Batata', 'Alberto Estrela', 1, 26).
ligacao('Lisandra Batata', 'Alberto Camara', 1, 16).
ligacao('Lisandra Batata', 'Diana Chaves', 3, 7).
ligacao('Lisandra Batata', 'Joao Prada', 2, 4).
ligacao('Lisandra Batata', 'Joao Medina', 3, 21).
ligacao('Lisandra Batata', 'Pilar Ouro', 2, -5).
ligacao('Alma Velasco', 'Carlos Moutinho', 1, 28).
ligacao('Alma Velasco', 'Breno Granja', 2, 34).
ligacao('Alma Velasco', 'Rodrigo Sousa', 3, 41).
ligacao('Alma Velasco', 'Andreia Sousa', 2, 46).
ligacao('Alma Velasco', 'Deolinda Varzeas', 2, 39).
ligacao('Alma Velasco', 'Beatriz Varzeas', 3, -7).
ligacao('Alma Velasco', 'Antonio Morais', 3, 30).
ligacao('Alma Velasco', 'Aurea Monsanto', 2, 12).
ligacao('Alma Velasco', 'Isabel Leite', 3, 31).
ligacao('Alma Velasco', 'Rosa Machado', 3, 47).
ligacao('Alma Velasco', 'Guilherme Araujo', 2, 8).
ligacao('Alma Velasco', 'Joana Araujo', 2, 32).
ligacao('Alma Velasco', 'Alberto Estrela', 1, 3).
ligacao('Alma Velasco', 'Alberto Camara', 2, 11).
ligacao('Alma Velasco', 'Diana Chaves', 3, 12).
ligacao('Alma Velasco', 'Joao Prada', 1, 21).
ligacao('Alma Velasco', 'Joao Medina', 3, 50).
ligacao('Alma Velasco', 'Pilar Ouro', 1, 28).
ligacao('Zavier Salomao', 'Carlos Moutinho', 1, 50).
ligacao('Zavier Salomao', 'Breno Granja', 3, 12).
ligacao('Zavier Salomao', 'Rodrigo Sousa', 1, 14).
ligacao('Zavier Salomao', 'Andreia Sousa', 3, -10).
ligacao('Zavier Salomao', 'Deolinda Varzeas', 3, 19).
ligacao('Zavier Salomao', 'Beatriz Varzeas', 3, 25).
ligacao('Zavier Salomao', 'Antonio Morais', 1, 14).
ligacao('Zavier Salomao', 'Aurea Monsanto', 3, -5).
ligacao('Zavier Salomao', 'Isabel Leite', 2, -7).
ligacao('Zavier Salomao', 'Rosa Machado', 2, -4).
ligacao('Zavier Salomao', 'Guilherme Araujo', 3, 28).
ligacao('Zavier Salomao', 'Joana Araujo', 2, 31).
ligacao('Zavier Salomao', 'Alberto Estrela', 1, 30).
ligacao('Zavier Salomao', 'Alberto Camara', 1, 47).
ligacao('Zavier Salomao', 'Diana Chaves', 2, 30).
ligacao('Zavier Salomao', 'Joao Prada', 1, 40).
ligacao('Zavier Salomao', 'Joao Medina', 1, 38).
ligacao('Zavier Salomao', 'Pilar Ouro', 1, 10).
ligacao('Xavier Alcaide', 'Carlos Moutinho', 3, 3).
ligacao('Xavier Alcaide', 'Breno Granja', 2, 33).
ligacao('Xavier Alcaide', 'Rodrigo Sousa', 3, 49).
ligacao('Xavier Alcaide', 'Andreia Sousa', 3, 32).
ligacao('Xavier Alcaide', 'Deolinda Varzeas', 1, -1).
ligacao('Xavier Alcaide', 'Beatriz Varzeas', 3, -3).
ligacao('Xavier Alcaide', 'Antonio Morais', 1, 37).
ligacao('Xavier Alcaide', 'Aurea Monsanto', 1, 7).
ligacao('Xavier Alcaide', 'Isabel Leite', 2, 40).
ligacao('Xavier Alcaide', 'Rosa Machado', 1, 37).
ligacao('Xavier Alcaide', 'Guilherme Araujo', 3, 50).
ligacao('Xavier Alcaide', 'Joana Araujo', 2, 4).
ligacao('Xavier Alcaide', 'Alberto Estrela', 3, 40).
ligacao('Xavier Alcaide', 'Alberto Camara', 2, 42).
ligacao('Xavier Alcaide', 'Diana Chaves', 3, 3).
ligacao('Xavier Alcaide', 'Joao Prada', 2, 25).
ligacao('Xavier Alcaide', 'Joao Medina', 3, 40).
ligacao('Xavier Alcaide', 'Pilar Ouro', 1, 14).
ligacao('Teresa Barbosa', 'Carlos Moutinho', 3, 9).
ligacao('Teresa Barbosa', 'Breno Granja', 2, 39).
ligacao('Teresa Barbosa', 'Rodrigo Sousa', 1, -4).
ligacao('Teresa Barbosa', 'Andreia Sousa', 1, 33).
ligacao('Teresa Barbosa', 'Deolinda Varzeas', 3, 1).
ligacao('Teresa Barbosa', 'Beatriz Varzeas', 1, 12).
ligacao('Teresa Barbosa', 'Antonio Morais', 3, 38).
ligacao('Teresa Barbosa', 'Aurea Monsanto', 3, 37).
ligacao('Teresa Barbosa', 'Isabel Leite', 2, 36).
ligacao('Teresa Barbosa', 'Rosa Machado', 1, 33).
ligacao('Teresa Barbosa', 'Guilherme Araujo', 3, 5).
ligacao('Teresa Barbosa', 'Joana Araujo', 2, 42).
ligacao('Teresa Barbosa', 'Alberto Estrela', 3, 48).
ligacao('Teresa Barbosa', 'Alberto Camara', 2, 34).
ligacao('Teresa Barbosa', 'Diana Chaves', 1, 33).
ligacao('Teresa Barbosa', 'Joao Prada', 2, 47).
ligacao('Teresa Barbosa', 'Joao Medina', 1, 30).
ligacao('Teresa Barbosa', 'Pilar Ouro', 3, 14).
ligacao('Helena Peixoto', 'Carlos Moutinho', 2, 16).
ligacao('Helena Peixoto', 'Breno Granja', 2, 48).
ligacao('Helena Peixoto', 'Rodrigo Sousa', 3, -3).
ligacao('Helena Peixoto', 'Andreia Sousa', 1, 18).
ligacao('Helena Peixoto', 'Deolinda Varzeas', 2, 29).
ligacao('Helena Peixoto', 'Beatriz Varzeas', 3, 26).
ligacao('Helena Peixoto', 'Antonio Morais', 2, 34).
ligacao('Helena Peixoto', 'Aurea Monsanto', 1, 46).
ligacao('Helena Peixoto', 'Isabel Leite', 2, 49).
ligacao('Helena Peixoto', 'Rosa Machado', 2, 10).
ligacao('Helena Peixoto', 'Guilherme Araujo', 1, 30).
ligacao('Helena Peixoto', 'Joana Araujo', 2, 9).
ligacao('Helena Peixoto', 'Alberto Estrela', 3, -6).
ligacao('Helena Peixoto', 'Alberto Camara', 1, 21).
ligacao('Helena Peixoto', 'Diana Chaves', 1, 12).
ligacao('Helena Peixoto', 'Joao Prada', 1, -8).
ligacao('Helena Peixoto', 'Joao Medina', 1, -1).
ligacao('Helena Peixoto', 'Pilar Ouro', 1, 10).
ligacao('Helena Sousa', 'Carlos Moutinho', 3, 28).
ligacao('Helena Sousa', 'Breno Granja', 3, 35).
ligacao('Helena Sousa', 'Rodrigo Sousa', 2, 39).
ligacao('Helena Sousa', 'Andreia Sousa', 2, 31).
ligacao('Helena Sousa', 'Deolinda Varzeas', 1, 34).
ligacao('Helena Sousa', 'Beatriz Varzeas', 2, 34).
ligacao('Helena Sousa', 'Antonio Morais', 2, 19).
ligacao('Helena Sousa', 'Aurea Monsanto', 3, 20).
ligacao('Helena Sousa', 'Isabel Leite', 3, 43).
ligacao('Helena Sousa', 'Rosa Machado', 3, -9).
ligacao('Helena Sousa', 'Guilherme Araujo', 2, 15).
ligacao('Helena Sousa', 'Joana Araujo', 1, 19).
ligacao('Helena Sousa', 'Alberto Estrela', 2, 36).
ligacao('Helena Sousa', 'Alberto Camara', 2, 18).
ligacao('Helena Sousa', 'Diana Chaves', 3, 10).
ligacao('Helena Sousa', 'Joao Prada', 2, 50).
ligacao('Helena Sousa', 'Joao Medina', 3, -6).
ligacao('Helena Sousa', 'Pilar Ouro', 1, 22).
ligacao('Soraia Couto', 'Carlos Moutinho', 2, 13).
ligacao('Soraia Couto', 'Breno Granja', 1, 50).
ligacao('Soraia Couto', 'Rodrigo Sousa', 2, 50).
ligacao('Soraia Couto', 'Andreia Sousa', 1, 47).
ligacao('Soraia Couto', 'Deolinda Varzeas', 3, 22).
ligacao('Soraia Couto', 'Beatriz Varzeas', 3, 9).
ligacao('Soraia Couto', 'Antonio Morais', 3, 20).
ligacao('Soraia Couto', 'Aurea Monsanto', 3, 16).
ligacao('Soraia Couto', 'Isabel Leite', 2, 40).
ligacao('Soraia Couto', 'Rosa Machado', 3, 22).
ligacao('Soraia Couto', 'Guilherme Araujo', 1, 10).
ligacao('Soraia Couto', 'Joana Araujo', 2, 26).
ligacao('Soraia Couto', 'Alberto Estrela', 2, 50).
ligacao('Soraia Couto', 'Alberto Camara', 2, 48).
ligacao('Soraia Couto', 'Diana Chaves', 1, 49).
ligacao('Soraia Couto', 'Joao Prada', 3, 7).
ligacao('Soraia Couto', 'Joao Medina', 2, 47).
ligacao('Soraia Couto', 'Pilar Ouro', 2, 45).
ligacao('Rosa Machado', 'Rui Mariske', 3, 17).
ligacao('Rosa Machado', 'Lisandra Batata', 1, 27).
ligacao('Rosa Machado', 'Alma Velasco', 3, -6).
ligacao('Rosa Machado', 'Zavier Salomao', 1, 26).
ligacao('Rosa Machado', 'Xavier Alcaide', 2, 5).
ligacao('Rosa Machado', 'Teresa Barbosa', 2, 9).
ligacao('Rosa Machado', 'Helena Peixoto', 3, 35).
ligacao('Rosa Machado', 'Helena Sousa', 3, -1).
ligacao('Rosa Machado', 'Soraia Couto', 3, 45).
ligacao('Rosa Machado', 'Telmo Catarino', 2, 14).
ligacao('Rosa Machado', 'Guilherme Vital', 1, 14).
ligacao('Rosa Machado', 'Rita Brandao', 2, 12).
ligacao('Rosa Machado', 'Sara Homem', 1, 0).
ligacao('Rosa Machado', 'Veronica Colaca', 1, 45).
ligacao('Rosa Machado', 'Emilia Monforte', 1, 10).
ligacao('Rosa Machado', 'Olivia Vidal', 3, 28).
ligacao('Rosa Machado', 'Tiara Lara', 3, -1).
ligacao('Rosa Machado', 'Veronica Neves', 1, 31).
ligacao('Guilherme Araujo', 'Rui Mariske', 1, 24).
ligacao('Guilherme Araujo', 'Lisandra Batata', 2, 11).
ligacao('Guilherme Araujo', 'Alma Velasco', 1, -10).
ligacao('Guilherme Araujo', 'Zavier Salomao', 3, 5).
ligacao('Guilherme Araujo', 'Xavier Alcaide', 2, 30).
ligacao('Guilherme Araujo', 'Teresa Barbosa', 1, 40).
ligacao('Guilherme Araujo', 'Helena Peixoto', 3, 25).
ligacao('Guilherme Araujo', 'Helena Sousa', 1, 8).
ligacao('Guilherme Araujo', 'Soraia Couto', 2, 18).
ligacao('Guilherme Araujo', 'Telmo Catarino', 3, 8).
ligacao('Guilherme Araujo', 'Guilherme Vital', 3, 45).
ligacao('Guilherme Araujo', 'Rita Brandao', 2, 12).
ligacao('Guilherme Araujo', 'Sara Homem', 3, 48).
ligacao('Guilherme Araujo', 'Veronica Colaca', 2, 28).
ligacao('Guilherme Araujo', 'Emilia Monforte', 1, 12).
ligacao('Guilherme Araujo', 'Olivia Vidal', 3, 14).
ligacao('Guilherme Araujo', 'Tiara Lara', 1, 24).
ligacao('Guilherme Araujo', 'Veronica Neves', 2, 44).
ligacao('Joana Araujo', 'Rui Mariske', 2, 45).
ligacao('Joana Araujo', 'Lisandra Batata', 3, 7).
ligacao('Joana Araujo', 'Alma Velasco', 3, 35).
ligacao('Joana Araujo', 'Zavier Salomao', 1, 7).
ligacao('Joana Araujo', 'Xavier Alcaide', 1, 49).
ligacao('Joana Araujo', 'Teresa Barbosa', 2, 0).
ligacao('Joana Araujo', 'Helena Peixoto', 1, -6).
ligacao('Joana Araujo', 'Helena Sousa', 1, -6).
ligacao('Joana Araujo', 'Soraia Couto', 1, 1).
ligacao('Joana Araujo', 'Telmo Catarino', 1, 21).
ligacao('Joana Araujo', 'Guilherme Vital', 3, 11).
ligacao('Joana Araujo', 'Rita Brandao', 2, 27).
ligacao('Joana Araujo', 'Sara Homem', 3, -5).
ligacao('Joana Araujo', 'Veronica Colaca', 3, -10).
ligacao('Joana Araujo', 'Emilia Monforte', 3, -9).
ligacao('Joana Araujo', 'Olivia Vidal', 1, 41).
ligacao('Joana Araujo', 'Tiara Lara', 1, 12).
ligacao('Joana Araujo', 'Veronica Neves', 2, 1).
ligacao('Alberto Estrela', 'Rui Mariske', 1, 47).
ligacao('Alberto Estrela', 'Lisandra Batata', 2, 34).
ligacao('Alberto Estrela', 'Alma Velasco', 3, -4).
ligacao('Alberto Estrela', 'Zavier Salomao', 2, -1).
ligacao('Alberto Estrela', 'Xavier Alcaide', 3, 22).
ligacao('Alberto Estrela', 'Teresa Barbosa', 2, 30).
ligacao('Alberto Estrela', 'Helena Peixoto', 1, 23).
ligacao('Alberto Estrela', 'Helena Sousa', 3, 20).
ligacao('Alberto Estrela', 'Soraia Couto', 2, 2).
ligacao('Alberto Estrela', 'Telmo Catarino', 2, 13).
ligacao('Alberto Estrela', 'Guilherme Vital', 3, 35).
ligacao('Alberto Estrela', 'Rita Brandao', 2, 31).
ligacao('Alberto Estrela', 'Sara Homem', 1, 20).
ligacao('Alberto Estrela', 'Veronica Colaca', 3, -4).
ligacao('Alberto Estrela', 'Emilia Monforte', 2, 50).
ligacao('Alberto Estrela', 'Olivia Vidal', 2, 11).
ligacao('Alberto Estrela', 'Tiara Lara', 2, 50).
ligacao('Alberto Estrela', 'Veronica Neves', 3, 50).
ligacao('Alberto Camara', 'Rui Mariske', 3, -4).
ligacao('Alberto Camara', 'Lisandra Batata', 3, 3).
ligacao('Alberto Camara', 'Alma Velasco', 2, 22).
ligacao('Alberto Camara', 'Zavier Salomao', 2, 29).
ligacao('Alberto Camara', 'Xavier Alcaide', 1, 0).
ligacao('Alberto Camara', 'Teresa Barbosa', 2, 11).
ligacao('Alberto Camara', 'Helena Peixoto', 2, 16).
ligacao('Alberto Camara', 'Helena Sousa', 2, 17).
ligacao('Alberto Camara', 'Soraia Couto', 3, -2).
ligacao('Alberto Camara', 'Telmo Catarino', 3, 3).
ligacao('Alberto Camara', 'Guilherme Vital', 1, 35).
ligacao('Alberto Camara', 'Rita Brandao', 2, -4).
ligacao('Alberto Camara', 'Sara Homem', 2, -6).
ligacao('Alberto Camara', 'Veronica Colaca', 3, 25).
ligacao('Alberto Camara', 'Emilia Monforte', 1, 42).
ligacao('Alberto Camara', 'Olivia Vidal', 2, 43).
ligacao('Alberto Camara', 'Tiara Lara', 2, 3).
ligacao('Alberto Camara', 'Veronica Neves', 2, 2).
ligacao('Diana Chaves', 'Rui Mariske', 2, 46).
ligacao('Diana Chaves', 'Lisandra Batata', 3, 11).
ligacao('Diana Chaves', 'Alma Velasco', 1, 30).
ligacao('Diana Chaves', 'Zavier Salomao', 3, 18).
ligacao('Diana Chaves', 'Xavier Alcaide', 3, -5).
ligacao('Diana Chaves', 'Teresa Barbosa', 2, 7).
ligacao('Diana Chaves', 'Helena Peixoto', 3, 14).
ligacao('Diana Chaves', 'Helena Sousa', 1, 1).
ligacao('Diana Chaves', 'Soraia Couto', 2, 5).
ligacao('Diana Chaves', 'Telmo Catarino', 2, 0).
ligacao('Diana Chaves', 'Guilherme Vital', 1, 7).
ligacao('Diana Chaves', 'Rita Brandao', 3, -7).
ligacao('Diana Chaves', 'Sara Homem', 2, 5).
ligacao('Diana Chaves', 'Veronica Colaca', 3, 21).
ligacao('Diana Chaves', 'Emilia Monforte', 2, -9).
ligacao('Diana Chaves', 'Olivia Vidal', 3, 25).
ligacao('Diana Chaves', 'Tiara Lara', 1, 12).
ligacao('Diana Chaves', 'Veronica Neves', 3, 49).
ligacao('Joao Prada', 'Rui Mariske', 3, 41).
ligacao('Joao Prada', 'Lisandra Batata', 1, 16).
ligacao('Joao Prada', 'Alma Velasco', 1, 19).
ligacao('Joao Prada', 'Zavier Salomao', 2, 23).
ligacao('Joao Prada', 'Xavier Alcaide', 2, 16).
ligacao('Joao Prada', 'Teresa Barbosa', 1, 44).
ligacao('Joao Prada', 'Helena Peixoto', 3, 45).
ligacao('Joao Prada', 'Helena Sousa', 2, 19).
ligacao('Joao Prada', 'Soraia Couto', 1, 7).
ligacao('Joao Prada', 'Telmo Catarino', 1, 41).
ligacao('Joao Prada', 'Guilherme Vital', 1, 0).
ligacao('Joao Prada', 'Rita Brandao', 1, 50).
ligacao('Joao Prada', 'Sara Homem', 2, 42).
ligacao('Joao Prada', 'Veronica Colaca', 1, -2).
ligacao('Joao Prada', 'Emilia Monforte', 3, 49).
ligacao('Joao Prada', 'Olivia Vidal', 1, 32).
ligacao('Joao Prada', 'Tiara Lara', 1, 32).
ligacao('Joao Prada', 'Veronica Neves', 2, 44).
ligacao('Joao Medina', 'Rui Mariske', 1, 4).
ligacao('Joao Medina', 'Lisandra Batata', 1, 42).
ligacao('Joao Medina', 'Alma Velasco', 3, -4).
ligacao('Joao Medina', 'Zavier Salomao', 3, 29).
ligacao('Joao Medina', 'Xavier Alcaide', 1, 1).
ligacao('Joao Medina', 'Teresa Barbosa', 1, 6).
ligacao('Joao Medina', 'Helena Peixoto', 2, 14).
ligacao('Joao Medina', 'Helena Sousa', 3, 17).
ligacao('Joao Medina', 'Soraia Couto', 2, 19).
ligacao('Joao Medina', 'Telmo Catarino', 1, 29).
ligacao('Joao Medina', 'Guilherme Vital', 3, 38).
ligacao('Joao Medina', 'Rita Brandao', 3, 12).
ligacao('Joao Medina', 'Sara Homem', 2, 31).
ligacao('Joao Medina', 'Veronica Colaca', 3, 41).
ligacao('Joao Medina', 'Emilia Monforte', 2, 41).
ligacao('Joao Medina', 'Olivia Vidal', 1, 27).
ligacao('Joao Medina', 'Tiara Lara', 3, 40).
ligacao('Joao Medina', 'Veronica Neves', 3, 12).
ligacao('Pilar Ouro', 'Rui Mariske', 2, 29).
ligacao('Pilar Ouro', 'Lisandra Batata', 2, 10).
ligacao('Pilar Ouro', 'Alma Velasco', 1, 0).
ligacao('Pilar Ouro', 'Zavier Salomao', 1, 36).
ligacao('Pilar Ouro', 'Xavier Alcaide', 3, 45).
ligacao('Pilar Ouro', 'Teresa Barbosa', 1, 35).
ligacao('Pilar Ouro', 'Helena Peixoto', 2, 27).
ligacao('Pilar Ouro', 'Helena Sousa', 1, 34).
ligacao('Pilar Ouro', 'Soraia Couto', 2, 20).
ligacao('Pilar Ouro', 'Telmo Catarino', 1, 47).
ligacao('Pilar Ouro', 'Guilherme Vital', 1, -8).
ligacao('Pilar Ouro', 'Rita Brandao', 2, 45).
ligacao('Pilar Ouro', 'Sara Homem', 3, 5).
ligacao('Pilar Ouro', 'Veronica Colaca', 1, 47).
ligacao('Pilar Ouro', 'Emilia Monforte', 2, 39).
ligacao('Pilar Ouro', 'Olivia Vidal', 2, -10).
ligacao('Pilar Ouro', 'Tiara Lara', 2, 29).
ligacao('Pilar Ouro', 'Veronica Neves', 1, 37).
ligacao('Telmo Catarino', 'Rosa Machado', 3, 2).
ligacao('Telmo Catarino', 'Guilherme Araujo', 1, -9).
ligacao('Telmo Catarino', 'Joana Araujo', 2, 45).
ligacao('Telmo Catarino', 'Alberto Estrela', 3, 29).
ligacao('Telmo Catarino', 'Alberto Camara', 1, 12).
ligacao('Telmo Catarino', 'Diana Chaves', 3, 34).
ligacao('Telmo Catarino', 'Joao Prada', 2, 32).
ligacao('Telmo Catarino', 'Joao Medina', 3, -4).
ligacao('Telmo Catarino', 'Pilar Ouro', 3, 27).
ligacao('Telmo Catarino', 'Maria Francisca', 1, 11).
ligacao('Telmo Catarino', 'Rui Duraes', 3, 47).
ligacao('Telmo Catarino', 'Rui Pedro', 1, -3).
ligacao('Telmo Catarino', 'Alice Monforte', 2, 21).
ligacao('Telmo Catarino', 'Antero Ouro', 2, 34).
ligacao('Telmo Catarino', 'Rafaela Uria', 3, 36).
ligacao('Telmo Catarino', 'Liliana Infante', 1, 15).
ligacao('Telmo Catarino', 'Augusto Bugalho', 1, -9).
ligacao('Telmo Catarino', 'Viriato Neto', 3, 7).
ligacao('Guilherme Vital', 'Rosa Machado', 3, 41).
ligacao('Guilherme Vital', 'Guilherme Araujo', 3, -4).
ligacao('Guilherme Vital', 'Joana Araujo', 1, 31).
ligacao('Guilherme Vital', 'Alberto Estrela', 3, 40).
ligacao('Guilherme Vital', 'Alberto Camara', 3, 29).
ligacao('Guilherme Vital', 'Diana Chaves', 1, 30).
ligacao('Guilherme Vital', 'Joao Prada', 1, 18).
ligacao('Guilherme Vital', 'Joao Medina', 3, 49).
ligacao('Guilherme Vital', 'Pilar Ouro', 2, 37).
ligacao('Guilherme Vital', 'Maria Francisca', 2, 40).
ligacao('Guilherme Vital', 'Rui Duraes', 1, 3).
ligacao('Guilherme Vital', 'Rui Pedro', 2, 16).
ligacao('Guilherme Vital', 'Alice Monforte', 2, 13).
ligacao('Guilherme Vital', 'Antero Ouro', 3, 46).
ligacao('Guilherme Vital', 'Rafaela Uria', 3, 18).
ligacao('Guilherme Vital', 'Liliana Infante', 1, 50).
ligacao('Guilherme Vital', 'Augusto Bugalho', 1, 41).
ligacao('Guilherme Vital', 'Viriato Neto', 3, 17).
ligacao('Rita Brandao', 'Rosa Machado', 3, 42).
ligacao('Rita Brandao', 'Guilherme Araujo', 2, 30).
ligacao('Rita Brandao', 'Joana Araujo', 3, 28).
ligacao('Rita Brandao', 'Alberto Estrela', 1, -6).
ligacao('Rita Brandao', 'Alberto Camara', 1, 33).
ligacao('Rita Brandao', 'Diana Chaves', 2, 26).
ligacao('Rita Brandao', 'Joao Prada', 2, -9).
ligacao('Rita Brandao', 'Joao Medina', 1, 8).
ligacao('Rita Brandao', 'Pilar Ouro', 1, 8).
ligacao('Rita Brandao', 'Maria Francisca', 1, 37).
ligacao('Rita Brandao', 'Rui Duraes', 1, 11).
ligacao('Rita Brandao', 'Rui Pedro', 1, 10).
ligacao('Rita Brandao', 'Alice Monforte', 2, 50).
ligacao('Rita Brandao', 'Antero Ouro', 1, -5).
ligacao('Rita Brandao', 'Rafaela Uria', 1, 48).
ligacao('Rita Brandao', 'Liliana Infante', 3, 35).
ligacao('Rita Brandao', 'Augusto Bugalho', 2, 1).
ligacao('Rita Brandao', 'Viriato Neto', 2, 15).
ligacao('Sara Homem', 'Rosa Machado', 2, 38).
ligacao('Sara Homem', 'Guilherme Araujo', 2, 19).
ligacao('Sara Homem', 'Joana Araujo', 2, 3).
ligacao('Sara Homem', 'Alberto Estrela', 1, 0).
ligacao('Sara Homem', 'Alberto Camara', 2, 38).
ligacao('Sara Homem', 'Diana Chaves', 3, 16).
ligacao('Sara Homem', 'Joao Prada', 1, 12).
ligacao('Sara Homem', 'Joao Medina', 3, -1).
ligacao('Sara Homem', 'Pilar Ouro', 1, 13).
ligacao('Sara Homem', 'Maria Francisca', 3, 47).
ligacao('Sara Homem', 'Rui Duraes', 1, 46).
ligacao('Sara Homem', 'Rui Pedro', 2, 23).
ligacao('Sara Homem', 'Alice Monforte', 1, 1).
ligacao('Sara Homem', 'Antero Ouro', 1, 20).
ligacao('Sara Homem', 'Rafaela Uria', 2, 38).
ligacao('Sara Homem', 'Liliana Infante', 3, -10).
ligacao('Sara Homem', 'Augusto Bugalho', 1, 20).
ligacao('Sara Homem', 'Viriato Neto', 1, 23).
ligacao('Veronica Colaca', 'Rosa Machado', 3, 5).
ligacao('Veronica Colaca', 'Guilherme Araujo', 3, 45).
ligacao('Veronica Colaca', 'Joana Araujo', 1, 5).
ligacao('Veronica Colaca', 'Alberto Estrela', 3, 41).
ligacao('Veronica Colaca', 'Alberto Camara', 2, -10).
ligacao('Veronica Colaca', 'Diana Chaves', 3, 37).
ligacao('Veronica Colaca', 'Joao Prada', 1, 41).
ligacao('Veronica Colaca', 'Joao Medina', 1, 22).
ligacao('Veronica Colaca', 'Pilar Ouro', 1, 40).
ligacao('Veronica Colaca', 'Maria Francisca', 1, 6).
ligacao('Veronica Colaca', 'Rui Duraes', 3, 6).
ligacao('Veronica Colaca', 'Rui Pedro', 3, -10).
ligacao('Veronica Colaca', 'Alice Monforte', 2, 12).
ligacao('Veronica Colaca', 'Antero Ouro', 2, 36).
ligacao('Veronica Colaca', 'Rafaela Uria', 2, 36).
ligacao('Veronica Colaca', 'Liliana Infante', 3, 44).
ligacao('Veronica Colaca', 'Augusto Bugalho', 2, 8).
ligacao('Veronica Colaca', 'Viriato Neto', 1, 46).
ligacao('Emilia Monforte', 'Rosa Machado', 3, 15).
ligacao('Emilia Monforte', 'Guilherme Araujo', 1, -4).
ligacao('Emilia Monforte', 'Joana Araujo', 2, -8).
ligacao('Emilia Monforte', 'Alberto Estrela', 2, 43).
ligacao('Emilia Monforte', 'Alberto Camara', 2, 33).
ligacao('Emilia Monforte', 'Diana Chaves', 2, 36).
ligacao('Emilia Monforte', 'Joao Prada', 2, 20).
ligacao('Emilia Monforte', 'Joao Medina', 1, -2).
ligacao('Emilia Monforte', 'Pilar Ouro', 2, 9).
ligacao('Emilia Monforte', 'Maria Francisca', 1, 27).
ligacao('Emilia Monforte', 'Rui Duraes', 3, 34).
ligacao('Emilia Monforte', 'Rui Pedro', 3, 48).
ligacao('Emilia Monforte', 'Alice Monforte', 3, 19).
ligacao('Emilia Monforte', 'Antero Ouro', 3, 25).
ligacao('Emilia Monforte', 'Rafaela Uria', 3, 47).
ligacao('Emilia Monforte', 'Liliana Infante', 1, -8).
ligacao('Emilia Monforte', 'Augusto Bugalho', 2, 46).
ligacao('Emilia Monforte', 'Viriato Neto', 2, -4).
ligacao('Olivia Vidal', 'Rosa Machado', 1, 44).
ligacao('Olivia Vidal', 'Guilherme Araujo', 2, -1).
ligacao('Olivia Vidal', 'Joana Araujo', 3, 47).
ligacao('Olivia Vidal', 'Alberto Estrela', 3, 26).
ligacao('Olivia Vidal', 'Alberto Camara', 2, 37).
ligacao('Olivia Vidal', 'Diana Chaves', 1, 17).
ligacao('Olivia Vidal', 'Joao Prada', 3, 23).
ligacao('Olivia Vidal', 'Joao Medina', 2, 25).
ligacao('Olivia Vidal', 'Pilar Ouro', 3, 18).
ligacao('Olivia Vidal', 'Maria Francisca', 2, 20).
ligacao('Olivia Vidal', 'Rui Duraes', 1, 14).
ligacao('Olivia Vidal', 'Rui Pedro', 3, 5).
ligacao('Olivia Vidal', 'Alice Monforte', 1, 44).
ligacao('Olivia Vidal', 'Antero Ouro', 2, 42).
ligacao('Olivia Vidal', 'Rafaela Uria', 1, 29).
ligacao('Olivia Vidal', 'Liliana Infante', 3, 26).
ligacao('Olivia Vidal', 'Augusto Bugalho', 3, 50).
ligacao('Olivia Vidal', 'Viriato Neto', 2, -10).
ligacao('Tiara Lara', 'Rosa Machado', 3, 26).
ligacao('Tiara Lara', 'Guilherme Araujo', 3, -2).
ligacao('Tiara Lara', 'Joana Araujo', 3, 5).
ligacao('Tiara Lara', 'Alberto Estrela', 2, 25).
ligacao('Tiara Lara', 'Alberto Camara', 3, -10).
ligacao('Tiara Lara', 'Diana Chaves', 1, 0).
ligacao('Tiara Lara', 'Joao Prada', 2, -3).
ligacao('Tiara Lara', 'Joao Medina', 1, 3).
ligacao('Tiara Lara', 'Pilar Ouro', 3, -3).
ligacao('Tiara Lara', 'Maria Francisca', 3, 8).
ligacao('Tiara Lara', 'Rui Duraes', 2, 40).
ligacao('Tiara Lara', 'Rui Pedro', 1, -2).
ligacao('Tiara Lara', 'Alice Monforte', 1, 34).
ligacao('Tiara Lara', 'Antero Ouro', 2, 3).
ligacao('Tiara Lara', 'Rafaela Uria', 2, 38).
ligacao('Tiara Lara', 'Liliana Infante', 2, 45).
ligacao('Tiara Lara', 'Augusto Bugalho', 3, 36).
ligacao('Tiara Lara', 'Viriato Neto', 2, -6).
ligacao('Veronica Neves', 'Rosa Machado', 2, 22).
ligacao('Veronica Neves', 'Guilherme Araujo', 2, 46).
ligacao('Veronica Neves', 'Joana Araujo', 3, 47).
ligacao('Veronica Neves', 'Alberto Estrela', 3, 27).
ligacao('Veronica Neves', 'Alberto Camara', 3, -5).
ligacao('Veronica Neves', 'Diana Chaves', 2, -7).
ligacao('Veronica Neves', 'Joao Prada', 1, 46).
ligacao('Veronica Neves', 'Joao Medina', 1, 4).
ligacao('Veronica Neves', 'Pilar Ouro', 2, 15).
ligacao('Veronica Neves', 'Maria Francisca', 3, -2).
ligacao('Veronica Neves', 'Rui Duraes', 1, -2).
ligacao('Veronica Neves', 'Rui Pedro', 3, 12).
ligacao('Veronica Neves', 'Alice Monforte', 2, 8).
ligacao('Veronica Neves', 'Antero Ouro', 2, 47).
ligacao('Veronica Neves', 'Rafaela Uria', 1, 14).
ligacao('Veronica Neves', 'Liliana Infante', 3, 40).
ligacao('Veronica Neves', 'Augusto Bugalho', 3, 43).
ligacao('Veronica Neves', 'Viriato Neto', 2, 32).
ligacao('Maria Francisca', 'Telmo Catarino', 1, 4).
ligacao('Maria Francisca', 'Guilherme Vital', 3, 16).
ligacao('Maria Francisca', 'Rita Brandao', 1, 35).
ligacao('Maria Francisca', 'Sara Homem', 2, 2).
ligacao('Maria Francisca', 'Veronica Colaca', 2, 34).
ligacao('Maria Francisca', 'Emilia Monforte', 3, 47).
ligacao('Maria Francisca', 'Olivia Vidal', 3, 49).
ligacao('Maria Francisca', 'Tiara Lara', 1, 1).
ligacao('Maria Francisca', 'Veronica Neves', 1, 22).
ligacao('Maria Francisca', 'Marta Teixeira', 3, 32).
ligacao('Maria Francisca', 'Dario Valverde', 1, 3).
ligacao('Maria Francisca', 'Estafania Pureza', 2, 14).
ligacao('Maria Francisca', 'Edna Jardim', 1, 43).
ligacao('Maria Francisca', 'Oscar Paixao', 1, 20).
ligacao('Maria Francisca', 'Luana Carvalho', 3, 35).
ligacao('Maria Francisca', 'Tania Negrao', 2, 38).
ligacao('Maria Francisca', 'Joao Cerveira', 3, 25).
ligacao('Maria Francisca', 'Pedro Sacramento', 1, 26).
ligacao('Rui Duraes', 'Telmo Catarino', 2, 7).
ligacao('Rui Duraes', 'Guilherme Vital', 3, -4).
ligacao('Rui Duraes', 'Rita Brandao', 1, -1).
ligacao('Rui Duraes', 'Sara Homem', 2, 32).
ligacao('Rui Duraes', 'Veronica Colaca', 1, -8).
ligacao('Rui Duraes', 'Emilia Monforte', 1, 31).
ligacao('Rui Duraes', 'Olivia Vidal', 2, 12).
ligacao('Rui Duraes', 'Tiara Lara', 3, 27).
ligacao('Rui Duraes', 'Veronica Neves', 2, 27).
ligacao('Rui Duraes', 'Marta Teixeira', 3, 0).
ligacao('Rui Duraes', 'Dario Valverde', 2, -9).
ligacao('Rui Duraes', 'Estafania Pureza', 3, 46).
ligacao('Rui Duraes', 'Edna Jardim', 1, 13).
ligacao('Rui Duraes', 'Oscar Paixao', 2, 50).
ligacao('Rui Duraes', 'Luana Carvalho', 1, 28).
ligacao('Rui Duraes', 'Tania Negrao', 2, 26).
ligacao('Rui Duraes', 'Joao Cerveira', 2, 39).
ligacao('Rui Duraes', 'Pedro Sacramento', 3, 23).
ligacao('Rui Pedro', 'Telmo Catarino', 1, 45).
ligacao('Rui Pedro', 'Guilherme Vital', 1, 21).
ligacao('Rui Pedro', 'Rita Brandao', 3, 10).
ligacao('Rui Pedro', 'Sara Homem', 2, -10).
ligacao('Rui Pedro', 'Veronica Colaca', 3, 44).
ligacao('Rui Pedro', 'Emilia Monforte', 3, 20).
ligacao('Rui Pedro', 'Olivia Vidal', 1, -7).
ligacao('Rui Pedro', 'Tiara Lara', 3, 6).
ligacao('Rui Pedro', 'Veronica Neves', 1, 20).
ligacao('Rui Pedro', 'Marta Teixeira', 3, 43).
ligacao('Rui Pedro', 'Dario Valverde', 3, 2).
ligacao('Rui Pedro', 'Estafania Pureza', 1, 9).
ligacao('Rui Pedro', 'Edna Jardim', 2, 8).
ligacao('Rui Pedro', 'Oscar Paixao', 1, 6).
ligacao('Rui Pedro', 'Luana Carvalho', 3, 42).
ligacao('Rui Pedro', 'Tania Negrao', 1, 11).
ligacao('Rui Pedro', 'Joao Cerveira', 2, 16).
ligacao('Rui Pedro', 'Pedro Sacramento', 1, 21).
ligacao('Alice Monforte', 'Telmo Catarino', 2, 4).
ligacao('Alice Monforte', 'Guilherme Vital', 3, 33).
ligacao('Alice Monforte', 'Rita Brandao', 3, -7).
ligacao('Alice Monforte', 'Sara Homem', 3, 7).
ligacao('Alice Monforte', 'Veronica Colaca', 1, 19).
ligacao('Alice Monforte', 'Emilia Monforte', 1, 20).
ligacao('Alice Monforte', 'Olivia Vidal', 1, 30).
ligacao('Alice Monforte', 'Tiara Lara', 1, 11).
ligacao('Alice Monforte', 'Veronica Neves', 3, 41).
ligacao('Alice Monforte', 'Marta Teixeira', 1, 31).
ligacao('Alice Monforte', 'Dario Valverde', 3, 36).
ligacao('Alice Monforte', 'Estafania Pureza', 3, -8).
ligacao('Alice Monforte', 'Edna Jardim', 3, 4).
ligacao('Alice Monforte', 'Oscar Paixao', 2, 49).
ligacao('Alice Monforte', 'Luana Carvalho', 2, 24).
ligacao('Alice Monforte', 'Tania Negrao', 1, -4).
ligacao('Alice Monforte', 'Joao Cerveira', 2, 1).
ligacao('Alice Monforte', 'Pedro Sacramento', 1, 46).
ligacao('Antero Ouro', 'Telmo Catarino', 2, 1).
ligacao('Antero Ouro', 'Guilherme Vital', 1, -5).
ligacao('Antero Ouro', 'Rita Brandao', 1, 50).
ligacao('Antero Ouro', 'Sara Homem', 2, 2).
ligacao('Antero Ouro', 'Veronica Colaca', 3, -3).
ligacao('Antero Ouro', 'Emilia Monforte', 2, 28).
ligacao('Antero Ouro', 'Olivia Vidal', 1, 24).
ligacao('Antero Ouro', 'Tiara Lara', 1, 49).
ligacao('Antero Ouro', 'Veronica Neves', 3, 36).
ligacao('Antero Ouro', 'Marta Teixeira', 1, 35).
ligacao('Antero Ouro', 'Dario Valverde', 3, 26).
ligacao('Antero Ouro', 'Estafania Pureza', 2, 10).
ligacao('Antero Ouro', 'Edna Jardim', 1, 1).
ligacao('Antero Ouro', 'Oscar Paixao', 2, 41).
ligacao('Antero Ouro', 'Luana Carvalho', 1, 1).
ligacao('Antero Ouro', 'Tania Negrao', 2, 25).
ligacao('Antero Ouro', 'Joao Cerveira', 3, 26).
ligacao('Antero Ouro', 'Pedro Sacramento', 2, 11).
ligacao('Rafaela Uria', 'Telmo Catarino', 2, 39).
ligacao('Rafaela Uria', 'Guilherme Vital', 2, 36).
ligacao('Rafaela Uria', 'Rita Brandao', 3, 43).
ligacao('Rafaela Uria', 'Sara Homem', 1, 34).
ligacao('Rafaela Uria', 'Veronica Colaca', 1, 26).
ligacao('Rafaela Uria', 'Emilia Monforte', 1, 38).
ligacao('Rafaela Uria', 'Olivia Vidal', 2, 2).
ligacao('Rafaela Uria', 'Tiara Lara', 2, -10).
ligacao('Rafaela Uria', 'Veronica Neves', 2, -3).
ligacao('Rafaela Uria', 'Marta Teixeira', 1, 3).
ligacao('Rafaela Uria', 'Dario Valverde', 3, 18).
ligacao('Rafaela Uria', 'Estafania Pureza', 3, 42).
ligacao('Rafaela Uria', 'Edna Jardim', 2, 24).
ligacao('Rafaela Uria', 'Oscar Paixao', 2, 0).
ligacao('Rafaela Uria', 'Luana Carvalho', 1, -7).
ligacao('Rafaela Uria', 'Tania Negrao', 1, 30).
ligacao('Rafaela Uria', 'Joao Cerveira', 2, -6).
ligacao('Rafaela Uria', 'Pedro Sacramento', 2, -8).
ligacao('Liliana Infante', 'Telmo Catarino', 3, 45).
ligacao('Liliana Infante', 'Guilherme Vital', 3, -7).
ligacao('Liliana Infante', 'Rita Brandao', 2, 29).
ligacao('Liliana Infante', 'Sara Homem', 2, 47).
ligacao('Liliana Infante', 'Veronica Colaca', 1, 33).
ligacao('Liliana Infante', 'Emilia Monforte', 3, 49).
ligacao('Liliana Infante', 'Olivia Vidal', 1, 2).
ligacao('Liliana Infante', 'Tiara Lara', 1, 38).
ligacao('Liliana Infante', 'Veronica Neves', 2, 17).
ligacao('Liliana Infante', 'Marta Teixeira', 3, 50).
ligacao('Liliana Infante', 'Dario Valverde', 3, 23).
ligacao('Liliana Infante', 'Estafania Pureza', 1, 2).
ligacao('Liliana Infante', 'Edna Jardim', 1, 31).
ligacao('Liliana Infante', 'Oscar Paixao', 2, 45).
ligacao('Liliana Infante', 'Luana Carvalho', 3, 34).
ligacao('Liliana Infante', 'Tania Negrao', 1, 6).
ligacao('Liliana Infante', 'Joao Cerveira', 3, 36).
ligacao('Liliana Infante', 'Pedro Sacramento', 3, 39).
ligacao('Augusto Bugalho', 'Telmo Catarino', 1, 3).
ligacao('Augusto Bugalho', 'Guilherme Vital', 3, 5).
ligacao('Augusto Bugalho', 'Rita Brandao', 1, -6).
ligacao('Augusto Bugalho', 'Sara Homem', 1, -10).
ligacao('Augusto Bugalho', 'Veronica Colaca', 1, 31).
ligacao('Augusto Bugalho', 'Emilia Monforte', 1, 23).
ligacao('Augusto Bugalho', 'Olivia Vidal', 3, 18).
ligacao('Augusto Bugalho', 'Tiara Lara', 2, 32).
ligacao('Augusto Bugalho', 'Veronica Neves', 2, 17).
ligacao('Augusto Bugalho', 'Marta Teixeira', 2, 3).
ligacao('Augusto Bugalho', 'Dario Valverde', 3, -8).
ligacao('Augusto Bugalho', 'Estafania Pureza', 2, 19).
ligacao('Augusto Bugalho', 'Edna Jardim', 2, 50).
ligacao('Augusto Bugalho', 'Oscar Paixao', 2, 26).
ligacao('Augusto Bugalho', 'Luana Carvalho', 3, 10).
ligacao('Augusto Bugalho', 'Tania Negrao', 1, -2).
ligacao('Augusto Bugalho', 'Joao Cerveira', 2, 14).
ligacao('Augusto Bugalho', 'Pedro Sacramento', 2, 18).
ligacao('Viriato Neto', 'Telmo Catarino', 2, 41).
ligacao('Viriato Neto', 'Guilherme Vital', 3, 39).
ligacao('Viriato Neto', 'Rita Brandao', 1, -7).
ligacao('Viriato Neto', 'Sara Homem', 2, -10).
ligacao('Viriato Neto', 'Veronica Colaca', 2, 7).
ligacao('Viriato Neto', 'Emilia Monforte', 3, 46).
ligacao('Viriato Neto', 'Olivia Vidal', 2, 2).
ligacao('Viriato Neto', 'Tiara Lara', 2, 22).
ligacao('Viriato Neto', 'Veronica Neves', 2, 23).
ligacao('Viriato Neto', 'Marta Teixeira', 2, 44).
ligacao('Viriato Neto', 'Dario Valverde', 2, -6).
ligacao('Viriato Neto', 'Estafania Pureza', 1, 18).
ligacao('Viriato Neto', 'Edna Jardim', 3, 0).
ligacao('Viriato Neto', 'Oscar Paixao', 3, -7).
ligacao('Viriato Neto', 'Luana Carvalho', 3, 5).
ligacao('Viriato Neto', 'Tania Negrao', 1, 50).
ligacao('Viriato Neto', 'Joao Cerveira', 3, 39).
ligacao('Viriato Neto', 'Pedro Sacramento', 3, 12).
ligacao('Marta Teixeira', 'Maria Francisca', 1, 1).
ligacao('Marta Teixeira', 'Rui Duraes', 3, 40).
ligacao('Marta Teixeira', 'Rui Pedro', 3, 18).
ligacao('Marta Teixeira', 'Alice Monforte', 3, 36).
ligacao('Marta Teixeira', 'Antero Ouro', 3, 32).
ligacao('Marta Teixeira', 'Rafaela Uria', 2, 4).
ligacao('Marta Teixeira', 'Liliana Infante', 1, 13).
ligacao('Marta Teixeira', 'Augusto Bugalho', 3, 30).
ligacao('Marta Teixeira', 'Viriato Neto', 2, 47).
ligacao('Marta Teixeira', 'Antonio Pedro', 1, 16).
ligacao('Marta Teixeira', 'Alma Braga', 3, -5).
ligacao('Marta Teixeira', 'Manuela Martinho', 3, 2).
ligacao('Marta Teixeira', 'Briana Toste', 2, 17).
ligacao('Marta Teixeira', 'Raquel Valverde', 3, -8).
ligacao('Marta Teixeira', 'Liana canela', 2, 32).
ligacao('Marta Teixeira', 'Sara Basilio', 2, 35).
ligacao('Marta Teixeira', 'Josefina Lamego', 1, 10).
ligacao('Marta Teixeira', 'Janice Adao', 1, 24).
ligacao('Dario Valverde', 'Maria Francisca', 2, 3).
ligacao('Dario Valverde', 'Rui Duraes', 3, 23).
ligacao('Dario Valverde', 'Rui Pedro', 2, 3).
ligacao('Dario Valverde', 'Alice Monforte', 2, 35).
ligacao('Dario Valverde', 'Antero Ouro', 1, 41).
ligacao('Dario Valverde', 'Rafaela Uria', 1, 47).
ligacao('Dario Valverde', 'Liliana Infante', 2, 29).
ligacao('Dario Valverde', 'Augusto Bugalho', 1, 19).
ligacao('Dario Valverde', 'Viriato Neto', 2, 45).
ligacao('Dario Valverde', 'Antonio Pedro', 1, 2).
ligacao('Dario Valverde', 'Alma Braga', 2, 0).
ligacao('Dario Valverde', 'Manuela Martinho', 1, 4).
ligacao('Dario Valverde', 'Briana Toste', 3, 0).
ligacao('Dario Valverde', 'Raquel Valverde', 1, 13).
ligacao('Dario Valverde', 'Liana canela', 1, 42).
ligacao('Dario Valverde', 'Sara Basilio', 2, 44).
ligacao('Dario Valverde', 'Josefina Lamego', 1, 22).
ligacao('Dario Valverde', 'Janice Adao', 1, 22).
ligacao('Estafania Pureza', 'Maria Francisca', 2, 8).
ligacao('Estafania Pureza', 'Rui Duraes', 2, -1).
ligacao('Estafania Pureza', 'Rui Pedro', 3, -3).
ligacao('Estafania Pureza', 'Alice Monforte', 2, 13).
ligacao('Estafania Pureza', 'Antero Ouro', 2, 22).
ligacao('Estafania Pureza', 'Rafaela Uria', 1, 11).
ligacao('Estafania Pureza', 'Liliana Infante', 2, 48).
ligacao('Estafania Pureza', 'Augusto Bugalho', 3, 31).
ligacao('Estafania Pureza', 'Viriato Neto', 2, 9).
ligacao('Estafania Pureza', 'Antonio Pedro', 1, -2).
ligacao('Estafania Pureza', 'Alma Braga', 1, 10).
ligacao('Estafania Pureza', 'Manuela Martinho', 2, 27).
ligacao('Estafania Pureza', 'Briana Toste', 3, 46).
ligacao('Estafania Pureza', 'Raquel Valverde', 3, 10).
ligacao('Estafania Pureza', 'Liana canela', 2, 40).
ligacao('Estafania Pureza', 'Sara Basilio', 1, 2).
ligacao('Estafania Pureza', 'Josefina Lamego', 3, 41).
ligacao('Estafania Pureza', 'Janice Adao', 3, 2).
ligacao('Edna Jardim', 'Maria Francisca', 3, 34).
ligacao('Edna Jardim', 'Rui Duraes', 2, 30).
ligacao('Edna Jardim', 'Rui Pedro', 2, -10).
ligacao('Edna Jardim', 'Alice Monforte', 3, 12).
ligacao('Edna Jardim', 'Antero Ouro', 1, 7).
ligacao('Edna Jardim', 'Rafaela Uria', 1, 30).
ligacao('Edna Jardim', 'Liliana Infante', 1, 18).
ligacao('Edna Jardim', 'Augusto Bugalho', 3, -6).
ligacao('Edna Jardim', 'Viriato Neto', 1, 29).
ligacao('Edna Jardim', 'Antonio Pedro', 3, 14).
ligacao('Edna Jardim', 'Alma Braga', 2, 37).
ligacao('Edna Jardim', 'Manuela Martinho', 2, 3).
ligacao('Edna Jardim', 'Briana Toste', 1, 33).
ligacao('Edna Jardim', 'Raquel Valverde', 1, 38).
ligacao('Edna Jardim', 'Liana canela', 3, 21).
ligacao('Edna Jardim', 'Sara Basilio', 2, -4).
ligacao('Edna Jardim', 'Josefina Lamego', 2, 38).
ligacao('Edna Jardim', 'Janice Adao', 2, 20).
ligacao('Oscar Paixao', 'Maria Francisca', 2, 4).
ligacao('Oscar Paixao', 'Rui Duraes', 3, 31).
ligacao('Oscar Paixao', 'Rui Pedro', 2, 10).
ligacao('Oscar Paixao', 'Alice Monforte', 2, 37).
ligacao('Oscar Paixao', 'Antero Ouro', 1, -9).
ligacao('Oscar Paixao', 'Rafaela Uria', 1, 19).
ligacao('Oscar Paixao', 'Liliana Infante', 1, 20).
ligacao('Oscar Paixao', 'Augusto Bugalho', 1, 12).
ligacao('Oscar Paixao', 'Viriato Neto', 3, 23).
ligacao('Oscar Paixao', 'Antonio Pedro', 3, 6).
ligacao('Oscar Paixao', 'Alma Braga', 2, -9).
ligacao('Oscar Paixao', 'Manuela Martinho', 2, 26).
ligacao('Oscar Paixao', 'Briana Toste', 1, 38).
ligacao('Oscar Paixao', 'Raquel Valverde', 3, -6).
ligacao('Oscar Paixao', 'Liana canela', 2, 44).
ligacao('Oscar Paixao', 'Sara Basilio', 1, -2).
ligacao('Oscar Paixao', 'Josefina Lamego', 2, -6).
ligacao('Oscar Paixao', 'Janice Adao', 1, 49).
ligacao('Luana Carvalho', 'Maria Francisca', 3, 37).
ligacao('Luana Carvalho', 'Rui Duraes', 2, -9).
ligacao('Luana Carvalho', 'Rui Pedro', 1, -6).
ligacao('Luana Carvalho', 'Alice Monforte', 2, 47).
ligacao('Luana Carvalho', 'Antero Ouro', 1, 49).
ligacao('Luana Carvalho', 'Rafaela Uria', 2, -9).
ligacao('Luana Carvalho', 'Liliana Infante', 3, 9).
ligacao('Luana Carvalho', 'Augusto Bugalho', 3, 19).
ligacao('Luana Carvalho', 'Viriato Neto', 1, 48).
ligacao('Luana Carvalho', 'Antonio Pedro', 2, 37).
ligacao('Luana Carvalho', 'Alma Braga', 2, -3).
ligacao('Luana Carvalho', 'Manuela Martinho', 3, 20).
ligacao('Luana Carvalho', 'Briana Toste', 1, 30).
ligacao('Luana Carvalho', 'Raquel Valverde', 1, -5).
ligacao('Luana Carvalho', 'Liana canela', 1, -7).
ligacao('Luana Carvalho', 'Sara Basilio', 2, -9).
ligacao('Luana Carvalho', 'Josefina Lamego', 2, 38).
ligacao('Luana Carvalho', 'Janice Adao', 3, 33).
ligacao('Tania Negrao', 'Maria Francisca', 1, 49).
ligacao('Tania Negrao', 'Rui Duraes', 2, 35).
ligacao('Tania Negrao', 'Rui Pedro', 1, 24).
ligacao('Tania Negrao', 'Alice Monforte', 1, 44).
ligacao('Tania Negrao', 'Antero Ouro', 2, 40).
ligacao('Tania Negrao', 'Rafaela Uria', 2, 29).
ligacao('Tania Negrao', 'Liliana Infante', 2, 32).
ligacao('Tania Negrao', 'Augusto Bugalho', 1, 41).
ligacao('Tania Negrao', 'Viriato Neto', 1, 44).
ligacao('Tania Negrao', 'Antonio Pedro', 3, 1).
ligacao('Tania Negrao', 'Alma Braga', 2, 44).
ligacao('Tania Negrao', 'Manuela Martinho', 2, 50).
ligacao('Tania Negrao', 'Briana Toste', 2, 30).
ligacao('Tania Negrao', 'Raquel Valverde', 3, 30).
ligacao('Tania Negrao', 'Liana canela', 2, 29).
ligacao('Tania Negrao', 'Sara Basilio', 1, 47).
ligacao('Tania Negrao', 'Josefina Lamego', 1, 7).
ligacao('Tania Negrao', 'Janice Adao', 3, 32).
ligacao('Joao Cerveira', 'Maria Francisca', 2, 37).
ligacao('Joao Cerveira', 'Rui Duraes', 3, -9).
ligacao('Joao Cerveira', 'Rui Pedro', 2, 22).
ligacao('Joao Cerveira', 'Alice Monforte', 3, 12).
ligacao('Joao Cerveira', 'Antero Ouro', 2, 17).
ligacao('Joao Cerveira', 'Rafaela Uria', 2, 14).
ligacao('Joao Cerveira', 'Liliana Infante', 1, 49).
ligacao('Joao Cerveira', 'Augusto Bugalho', 2, 18).
ligacao('Joao Cerveira', 'Viriato Neto', 3, 45).
ligacao('Joao Cerveira', 'Antonio Pedro', 1, 42).
ligacao('Joao Cerveira', 'Alma Braga', 2, 41).
ligacao('Joao Cerveira', 'Manuela Martinho', 2, 49).
ligacao('Joao Cerveira', 'Briana Toste', 3, 25).
ligacao('Joao Cerveira', 'Raquel Valverde', 1, 1).
ligacao('Joao Cerveira', 'Liana canela', 2, 17).
ligacao('Joao Cerveira', 'Sara Basilio', 2, 19).
ligacao('Joao Cerveira', 'Josefina Lamego', 2, -6).
ligacao('Joao Cerveira', 'Janice Adao', 2, 42).
ligacao('Pedro Sacramento', 'Maria Francisca', 2, 35).
ligacao('Pedro Sacramento', 'Rui Duraes', 2, 10).
ligacao('Pedro Sacramento', 'Rui Pedro', 3, 40).
ligacao('Pedro Sacramento', 'Alice Monforte', 2, -2).
ligacao('Pedro Sacramento', 'Antero Ouro', 3, 33).
ligacao('Pedro Sacramento', 'Rafaela Uria', 2, 48).
ligacao('Pedro Sacramento', 'Liliana Infante', 3, 11).
ligacao('Pedro Sacramento', 'Augusto Bugalho', 1, -5).
ligacao('Pedro Sacramento', 'Viriato Neto', 2, 13).
ligacao('Pedro Sacramento', 'Antonio Pedro', 1, -2).
ligacao('Pedro Sacramento', 'Alma Braga', 2, 4).
ligacao('Pedro Sacramento', 'Manuela Martinho', 2, 42).
ligacao('Pedro Sacramento', 'Briana Toste', 2, 36).
ligacao('Pedro Sacramento', 'Raquel Valverde', 1, -5).
ligacao('Pedro Sacramento', 'Liana canela', 3, -7).
ligacao('Pedro Sacramento', 'Sara Basilio', 2, 41).
ligacao('Pedro Sacramento', 'Josefina Lamego', 3, 26).
ligacao('Pedro Sacramento', 'Janice Adao', 3, 4).
ligacao('Antonio Pedro', 'Pedro Mourao', 2, 2).
ligacao('Antonio Pedro', 'Marta Teixeira', 3, 26).
ligacao('Antonio Pedro', 'Dario Valverde', 1, 40).
ligacao('Antonio Pedro', 'Estafania Pureza', 3, 19).
ligacao('Antonio Pedro', 'Edna Jardim', 2, 18).
ligacao('Antonio Pedro', 'Oscar Paixao', 1, 36).
ligacao('Antonio Pedro', 'Luana Carvalho', 3, -1).
ligacao('Antonio Pedro', 'Tania Negrao', 1, -7).
ligacao('Antonio Pedro', 'Joao Cerveira', 3, 34).
ligacao('Antonio Pedro', 'Pedro Sacramento', 1, 38).
ligacao('Alma Braga', 'Pedro Mourao', 2, 38).
ligacao('Alma Braga', 'Marta Teixeira', 2, 32).
ligacao('Alma Braga', 'Dario Valverde', 1, 49).
ligacao('Alma Braga', 'Estafania Pureza', 3, 46).
ligacao('Alma Braga', 'Edna Jardim', 1, 15).
ligacao('Alma Braga', 'Oscar Paixao', 1, -2).
ligacao('Alma Braga', 'Luana Carvalho', 2, -7).
ligacao('Alma Braga', 'Tania Negrao', 3, 49).
ligacao('Alma Braga', 'Joao Cerveira', 2, 23).
ligacao('Alma Braga', 'Pedro Sacramento', 1, 26).
ligacao('Manuela Martinho', 'Pedro Mourao', 1, 16).
ligacao('Manuela Martinho', 'Marta Teixeira', 1, 6).
ligacao('Manuela Martinho', 'Dario Valverde', 1, 46).
ligacao('Manuela Martinho', 'Estafania Pureza', 3, 16).
ligacao('Manuela Martinho', 'Edna Jardim', 1, 13).
ligacao('Manuela Martinho', 'Oscar Paixao', 3, -8).
ligacao('Manuela Martinho', 'Luana Carvalho', 2, -1).
ligacao('Manuela Martinho', 'Tania Negrao', 1, 17).
ligacao('Manuela Martinho', 'Joao Cerveira', 1, 42).
ligacao('Manuela Martinho', 'Pedro Sacramento', 1, 42).
ligacao('Briana Toste', 'Pedro Mourao', 2, 27).
ligacao('Briana Toste', 'Marta Teixeira', 1, 42).
ligacao('Briana Toste', 'Dario Valverde', 1, 21).
ligacao('Briana Toste', 'Estafania Pureza', 1, 43).
ligacao('Briana Toste', 'Edna Jardim', 3, 44).
ligacao('Briana Toste', 'Oscar Paixao', 2, 42).
ligacao('Briana Toste', 'Luana Carvalho', 2, 17).
ligacao('Briana Toste', 'Tania Negrao', 1, 27).
ligacao('Briana Toste', 'Joao Cerveira', 1, 28).
ligacao('Briana Toste', 'Pedro Sacramento', 1, 8).
ligacao('Raquel Valverde', 'Pedro Mourao', 2, 23).
ligacao('Raquel Valverde', 'Marta Teixeira', 3, 44).
ligacao('Raquel Valverde', 'Dario Valverde', 2, 46).
ligacao('Raquel Valverde', 'Estafania Pureza', 1, -4).
ligacao('Raquel Valverde', 'Edna Jardim', 3, 40).
ligacao('Raquel Valverde', 'Oscar Paixao', 2, 4).
ligacao('Raquel Valverde', 'Luana Carvalho', 2, 4).
ligacao('Raquel Valverde', 'Tania Negrao', 2, 28).
ligacao('Raquel Valverde', 'Joao Cerveira', 2, 2).
ligacao('Raquel Valverde', 'Pedro Sacramento', 2, -3).
ligacao('Liana canela', 'Pedro Mourao', 1, 12).
ligacao('Liana canela', 'Marta Teixeira', 2, 38).
ligacao('Liana canela', 'Dario Valverde', 3, 0).
ligacao('Liana canela', 'Estafania Pureza', 2, -4).
ligacao('Liana canela', 'Edna Jardim', 1, 49).
ligacao('Liana canela', 'Oscar Paixao', 2, 32).
ligacao('Liana canela', 'Luana Carvalho', 2, 12).
ligacao('Liana canela', 'Tania Negrao', 2, 46).
ligacao('Liana canela', 'Joao Cerveira', 3, 12).
ligacao('Liana canela', 'Pedro Sacramento', 1, 38).
ligacao('Sara Basilio', 'Pedro Mourao', 2, 19).
ligacao('Sara Basilio', 'Marta Teixeira', 1, 38).
ligacao('Sara Basilio', 'Dario Valverde', 2, -9).
ligacao('Sara Basilio', 'Estafania Pureza', 3, 20).
ligacao('Sara Basilio', 'Edna Jardim', 3, 22).
ligacao('Sara Basilio', 'Oscar Paixao', 1, -5).
ligacao('Sara Basilio', 'Luana Carvalho', 2, 48).
ligacao('Sara Basilio', 'Tania Negrao', 3, 13).
ligacao('Sara Basilio', 'Joao Cerveira', 1, 30).
ligacao('Sara Basilio', 'Pedro Sacramento', 3, 48).
ligacao('Josefina Lamego', 'Pedro Mourao', 3, 5).
ligacao('Josefina Lamego', 'Marta Teixeira', 3, 15).
ligacao('Josefina Lamego', 'Dario Valverde', 1, 45).
ligacao('Josefina Lamego', 'Estafania Pureza', 2, 43).
ligacao('Josefina Lamego', 'Edna Jardim', 3, 2).
ligacao('Josefina Lamego', 'Oscar Paixao', 2, 42).
ligacao('Josefina Lamego', 'Luana Carvalho', 3, 12).
ligacao('Josefina Lamego', 'Tania Negrao', 3, 47).
ligacao('Josefina Lamego', 'Joao Cerveira', 1, 28).
ligacao('Josefina Lamego', 'Pedro Sacramento', 1, -7).
ligacao('Janice Adao', 'Pedro Mourao', 1, 40).
ligacao('Janice Adao', 'Marta Teixeira', 1, -7).
ligacao('Janice Adao', 'Dario Valverde', 3, 40).
ligacao('Janice Adao', 'Estafania Pureza', 2, 25).
ligacao('Janice Adao', 'Edna Jardim', 2, 28).
ligacao('Janice Adao', 'Oscar Paixao', 2, 16).
ligacao('Janice Adao', 'Luana Carvalho', 3, 29).
ligacao('Janice Adao', 'Tania Negrao', 1, -6).
ligacao('Janice Adao', 'Joao Cerveira', 3, 3).
ligacao('Janice Adao', 'Pedro Sacramento', 2, 49).
